### ISSUE TITLE
bug in guessdatetimefstr

### ISSUE THREAD

**Issue by geier** [pimutils/khal#1039]
```
(khal) (base) (git)[pr/1037(32)|…3⚑1]% khal at "12.05.2021 22:30"                                                                                                                                   ~/workspace/khal
Traceback (most recent call last):
  File "/Users/cg/.virtualenvs/khal/bin/khal", line 33, in <module>
    sys.exit(load_entry_point('khal', 'console_scripts', 'khal')())
  File "/Users/cg/.virtualenvs/khal/lib/python3.8/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cg/.virtualenvs/khal/lib/python3.8/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/cg/.virtualenvs/khal/lib/python3.8/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cg/.virtualenvs/khal/lib/python3.8/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cg/.virtualenvs/khal/lib/python3.8/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/cg/.virtualenvs/khal/lib/python3.8/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cg/workspace/khal/khal/cli.py", line 642, in at
    rows = controllers.khal_list(
  File "/Users/cg/workspace/khal/khal/controllers.py", line 240, in khal_list
    start, allday = parse_datetime.guessdatetimefstr(
  File "/Users/cg/workspace/khal/khal/parse_datetime.py", line 234, in guessdatetimefstr
    dtstart = fun(dtime_list, dtformat, infer_year=infer_year)
  File "/Users/cg/workspace/khal/khal/parse_datetime.py", line 217, in datefstr_year
    return datetimefstr(dtime_list, dtformat, default_day, infer_year, in_future)
  File "/Users/cg/workspace/khal/khal/parse_datetime.py", line 83, in datetimefstr
    dtime_list.pop(0)
IndexError: pop from empty list
```

The issue here is the \" around the date and time. At least show an error message, not an exception.

**Comment by ephase** [comment]
Hi @geier one possible solution is adding a simple test like that in `cli.py` 

```python
    def at(ctx, datetime, notstarted, format, day_format, include_calendar, exclude_calendar):
        '''Print all events at a specific datetime (defaults to now).'''
        if not datetime:
            datetime = ("now",)
        elif len(datetime) == 1:
            ''' avoid problem with double-quoted argument'''
            datetime=datetime[0].split()
        try:
```python

Another option could be throw an error if `len(datetime)` equal 1.
