### ISSUE TITLE
Can't import ics file

### ISSUE THREAD

**Issue by N0ury** [pimutils/khal#1069]
Hi,

When importing an ics file to a calendar, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/khal", line 33, in <module>
    sys.exit(load_entry_point('khal==0.10.3', 'console_scripts', 'khal')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/khal/cli.py", line 452, in import_ics
    controllers.import_ics(
  File "/usr/lib/python3/dist-packages/khal/controllers.py", line 567, in import_ics
    vevents = split_ics(ics, random_uid, conf['locale']['default_timezone'])
  File "/usr/lib/python3/dist-packages/khal/icalendar.py", line 48, in split_ics
    cal = cal_from_ics(ics)
  File "/usr/lib/python3/dist-packages/khal/icalendar.py", line 524, in cal_from_ics
    return cal
UnboundLocalError: local variable 'cal' referenced before assignment
```

Here's the content of the ics file:
========= begin =============
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
 
BEGIN:VEVENT 
DTSTART;VALUE=DATE:20210530 
DTEND;VALUE=DATE:20210530 
SUMMARY:Fete des Meres 
DTSTAMP:20210530T000000Z 
CREATED:20210530T000000Z 
END:VEVENT
 
END:VCALENDAR
```
========= end ===============

Anyone can help me?

**Comment by N0ury** [comment]
Date format was wrong and there is a space at the end of the line.
I close the issue.
