### ISSUE TITLE
Incompatibility with tzlocal-3

### ISSUE THREAD

**Issue by ajakk** [pimutils/khal#1081]
Running certain khal invocations with 0.10.4 and from Git with tzlocal-3 installed crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/khal", line 33, in <module>
    sys.exit(load_entry_point('khal==0.10.4', 'console_scripts', 'khal')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/khal/cli.py", line 470, in interactive
    controllers.interactive(
  File "/usr/lib/python3.9/site-packages/khal/controllers.py", line 545, in interactive
    pane = ui.ClassicView(
  File "/usr/lib/python3.9/site-packages/khal/ui/__init__.py", line 1045, in __init__
    daywalker = Walker(
  File "/usr/lib/python3.9/site-packages/khal/ui/__init__.py", line 361, in __init__
    self.ensure_date(this_date)
  File "/usr/lib/python3.9/site-packages/khal/ui/__init__.py", line 370, in ensure_date
    pile = self._get_events(day)
  File "/usr/lib/python3.9/site-packages/khal/ui/__init__.py", line 480, in _get_events
    self.events = sorted(self._collection.get_events_on(day))
  File "/usr/lib/python3.9/site-packages/khal/khalendar/khalendar.py", line 152, in get_events_on
    localize = self._locale['local_timezone'].localize
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'
```

Presumably this is because of [tzlocal-3 switching timezone providers to zoneinfo](https://github.com/regebro/tzlocal/blob/master/CHANGES.txt#L22). Downgrading back to 2.1 (earliest packaged in Gentoo) fixes the issue.

**Comment by ajakk** [comment]
Sorry, this is a duplicate.
