### ISSUE TITLE
Documentation mentions an unworking command

### ISSUE THREAD

**Issue by mathstuf** [pimutils/khal#1084]
Reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1998868

The command in `doc/source/usage.rst` mentions a command `khal new 25.10. 18:00 24:00 Another Event :: with Alice and Bob` which ends up with a backtrace;

```
Traceback (most recent call last):
  File "/usr/bin/khal", line 33, in <module>
    sys.exit(load_entry_point('khal==0.9.10', 'console_scripts', 'khal')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/khal/cli.py", line 386, in new
    new_func(
  File "/usr/lib/python3.9/site-packages/khal/controllers.py", line 339, in new_from_string
    info = utils.eventinfofstr(info, conf['locale'], adjust_reasonably=True, localize=False)
  File "/usr/lib/python3.9/site-packages/khal/utils.py", line 521, in eventinfofstr
    raise ValueError('Could not parse `{}`'.format(info_string))
ValueError: Could not parse `25.10. 18:00 24:00 Another Event
```

**Comment by d7415** [comment]
From the start of that section: `These may need to be adapted for your configuration and/or locale`

**Comment by d7415** [comment]
(See #884)
