### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by ECon87** [pimutils/khal#1088]
I accidentally exited the app without saving an event. Now I cannot get it to work again.

Any advice would be greatly appreciated!

Full error:

```
Traceback (most recent call last):
  File "/path/bin/khal", line 8, in <module>
    sys.exit(main_khal())
  File "/path/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/path/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/path/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/path/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/path/lib/python3.9/site-packages/khal/cli.py", line 600, in edit
    build_collection(
  File "/path/lib/python3.9/site-packages/khal/cli.py", line 169, in build_collection
    collection = khalendar.CalendarCollection(
  File "/path/lib/python3.9/site-packages/khal/khalendar/khalendar.py", line 103, in __init__
    self.update_db()
  File "/path/lib/python3.9/site-packages/khal/khalendar/khalendar.py", line 269, in update_db
    self._db_update(calendar)
  File "/path/lib/python3.9/site-packages/khal/khalendar/khalendar.py", line 326, in _db_update
    self._backend.delete(href, calendar=calendar)
  File "/path/lib/python3.9/site-packages/khal/khalendar/backend.py", line 432, in delete
    self.sql_ex(sql_s, (href, calendar))
  File "/path/lib/python3.9/site-packages/khal/khalendar/backend.py", line 192, in sql_ex
    self.cursor.execute(statement, stuple)
sqlite3.OperationalError: database is locked

```

**Comment by geier** [comment]
Sorry for the late reply. 

If this is still relevant:

You can delete the sqlite database, it is used as a cache and deleting it doesn't lead to data loss. You find the location of the database by running khal in debug mode, e.g. `khal -v DEBUG calendar`. The database path is in the [sqlite] section of the dumped config under `path`. Hope this helps.
