### ISSUE TITLE
RuntimeError: You need Click 5.0.

### ISSUE THREAD

**Issue by muralikodali** [pimutils/khal#1133]
I have recently installed python 3.10.4 and upgraded all packages.

```sh
khal list
```
is giving following error : 

```
Traceback (most recent call last):
  File "/home/murali/.local/bin/khal", line 5, in <module>
    from khal.cli import main_khal
  File "/home/murali/.local/lib/python3.10/site-packages/khal/cli.py", line 31, in <module>
    import click_log
  File "/home/murali/.local/lib/python3.10/site-packages/click_log/__init__.py", line 10, in <module>
    raise RuntimeError('You need Click 5.0.')
RuntimeError: You need Click 5.0.
```

click version is : 8.1.3

**Comment by muralikodali** [comment]
```sh
$ pip --version
pip 22.1 from /home/murali/.local/lib/python3.10/site-packages/pip (python 3.10)
```
```sh
$ pip freeze | grep click
click==8.1.3
click-didyoumean==0.3.0
click-log==0.3.2
click-plugins==1.1.1
click-repl==0.2.0
click-spinner==0.1.10
click-threading==0.5.0
```

**Comment by WhyNotHugo** [comment]
Odd. The versions all seem correct, and it doesn't look like different environments are being mixed up.

If you run a `python` shell and then run `import click; print(click.__version__)`, does that match? What does `hasattr(click, 'get_current_context')` show?

**Comment by geier** [comment]
Please re-open if this continues to be an issue.
