### ISSUE TITLE
error: ('CREATED', "Expected datetime, date, or time, got: 'None'") when importing ics file

### ISSUE THREAD

**Issue by heapifyman** [pimutils/khal#1138]
**Steps to reproduce**

1. `khal import error_when_importing.ics` - see [error_when_importing.ics.txt](https://github.com/pimutils/khal/files/8933434/error_when_importing.ics.txt) (renamed because github does not allow attaching .ics files)

**Result**

```
error: Errors occurred when parsing my_calendar/6RELAm7jx9B2Kn2Tl0AbKbNXGWJv8pMk.ics for the following reasons:
error: ('CREATED', "Expected datetime, date, or time, got: 'None'")
error: ('LAST-MODIFIED', "Expected datetime, date, or time, got: 'None'")
error: This might lead to this event being shown wrongly or not at all.
```

The resulting event then indeed has CREATED and LAST_MODIFIED set to None. Even though the original  `error_when_importing.ics` file does not.

When I try to edit and save the event in `ikhal`, it crashes with the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1358, in start_pane
    loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.10/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.10/site-packages/khal/ui/editor.py", line 530, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.10/site-packages/khal/ui/widgets.py", line 376, in keypress
    key = super().keypress(size, key)
  File "/usr/lib/python3.10/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.10/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/usr/lib/python3.10/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.10/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.10/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.10/site-packages/khal/ui/editor.py", line 510, in save
    self.collection.update(self.event)
  File "/usr/lib/python3.10/site-packages/khal/khalendar/khalendar.py", line 173, in update
    self._backend.update(event.raw, event.href, event.etag, calendar=event.calendar)
  File "/usr/lib/python3.10/site-packages/khal/khalendar/backend.py", line 237, in update
    check_for_errors(vevent, calendar, href)
  File "/usr/lib/python3.10/site-packages/khal/khalendar/backend.py", line 638, in check_for_errors
    logger.error(error)
  File "/usr/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1302, in emit
    frame.log(self.format(record))
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1291, in format
    return (self.get_prefix(record.levelno) + ': ' + record.msg)
TypeError: can only concatenate str (not "tuple") to str
```

**Expected result**

Event should be imported without errors. It should be possible to edit the event without crashes.

**Additional info**

This might be related to #1107 because `error_when_importing.ics` seems to contain identical RRULE entries, although this is not a repeating event.

**Comment by d7415** [comment]
Was that file manually created/edited? As far as I can tell, date-times in ICS format shouldn't have a separator (like `-`). This is specified in [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.4) and only the two fields that are causing errors in that file have them.

**Comment by heapifyman** [comment]
I received the file by email after making an appointment online. I therefore assume it was generated automatically.
I edited the location and some other fields before uploading it here. But I did not touch the CREATED or LAST_MODIFIED fields.
Both [etar](https://f-droid.org/en/packages/ws.xsoh.etar/) and Outlook imported the file without issues.

**Comment by geier** [comment]
We probably should just ignore those fields if they are invalid. At the very least, we shouldn't crash on them.

**Comment by geier** [comment]
For now, we'll deal with the crashing and keep track of fixing broken event in #1140
