### ISSUE TITLE
ikhal Crashes when trying to delete Multiple Events

### ISSUE THREAD

**Issue by BioBox** [pimutils/khal#1184]
I have two repeating events and I want to delete a single occurance for both of them on a certain day.
I mark the two of them for deletion (shows a d next to title), and when I quit I get this:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1365, in start_pane
    loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 519, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 565, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/lib/python3.10/site-packages/khal/ui/base.py", line 205, in on_key_press
    self.backtrack()
  File "/usr/lib/python3.10/site-packages/khal/ui/base.py", line 190, in backtrack
    cb(data)
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1119, in cleanup
    self.collection.update(event)
  File "/usr/lib/python3.10/site-packages/khal/khalendar/khalendar.py", line 170, in update
    assert event.etag
AssertionError
```

Nothing happens to the events I want deleted.
Try to replicate this and comment what you get. Thanks!

**Comment by BioBox** [comment]
Interestingly, this bug doesn't occur on python 3.9.10. I don't know whether this is due to a change in python or because there was a commit that fixed this. Definitely helps to know these things.

**Comment by WhyNotHugo** [comment]
Hard to know without knowing which version of khal, python, and dependencies you were using when this originally happened.

I see no relevant commits since September, assuming you follow master.
