### ISSUE TITLE
Khal crashes, adding a repeating event

### ISSUE THREAD

**Issue by jdnumm** [pimutils/khal#1187]
```
khal, version 0.10.5

khal new tuesday 14:30 150 -r weekly "text"
Traceback (most recent call last):
  File "/home/mono/.local/bin/khal", line 8, in <module>
    sys.exit(main_khal())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mono/.local/lib/python3.10/site-packages/khal/cli.py", line 394, in new
    new_func(
  File "/home/mono/.local/lib/python3.10/site-packages/khal/controllers.py", line 378, in new_from_string
    new_from_args(
  File "/home/mono/.local/lib/python3.10/site-packages/khal/controllers.py", line 393, in new_from_args
    event = new_vevent(
  File "/home/mono/.local/lib/python3.10/site-packages/khal/icalendar.py", line 132, in new_event
    rrule = rrulefstr(repeat, until, locale, dtstart.tzinfo)
AttributeError: 'datetime.date' object has no attribute 'tzinfo'
```

**Comment by tjensch** [comment]
I experience similar issues. 
I've set up events with roundcube (1.4.13-6.4.el7.kolab_16) and aCalendar+ (2.6.1). 
On first sight, recurring events of the type "Repeat Every X day(s), for X time(s)" do work, but recurring events of the type "Repeat Every X week(s), until xxx" dont. 
Also events of the type "Repeat [ondate]" dont work, but this option is only available with roundcube and additionally screws up the time of the event when synced to aCalender+.

**Comment by Iss-in** [comment]
similar trouble here as well

**Comment by geier** [comment]
Thank you for reporting these issues. Unfortunately, I cannot reproduce them on my end. It also looks to me, like @jdnumm  and @tjensch have different issues (but the stack trace looks similar).

**Comment by geier** [comment]
If those are still issues, please open new issues with the information requested by the new issue template.
