### ISSUE TITLE
Crassh importing Holiday file

### ISSUE THREAD

**Issue by garyemiller** [pimutils/khal#1199]
I'm new to khal, and liking it.  I have 0.10.5 from the Gentoo package.  Got adventurous and tried to import an ical file of US Holidays.  Not so good...

```
# khal --version
khal, version 0.10.5

# python -V
Python 3.10.8

# khal import /tmp/USHolidays.ics
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/khal", line 8, in <module>
    sys.exit(main_khal())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/khal/cli.py", line 465, in import_ics
    controllers.import_ics(
  File "/usr/lib/python3.10/site-packages/khal/controllers.py", line 595, in import_ics
    vevents = split_ics(ics, random_uid, conf['locale']['default_timezone'])
  File "/usr/lib/python3.10/site-packages/khal/icalendar.py", line 76, in split_ics
    return [ics_from_list(events, tzs, random_uid, default_timezone) for uid, events in
  File "/usr/lib/python3.10/site-packages/khal/icalendar.py", line 76, in <listcomp>
    return [ics_from_list(events, tzs, random_uid, default_timezone) for uid, events in
  File "/usr/lib/python3.10/site-packages/khal/icalendar.py", line 167, in ics_from_list
    sub_event = sanitize(sub_event, default_timezone=default_timezone)
  File "/usr/lib/python3.10/site-packages/khal/icalendar.py", line 395, in sanitize
    dtstart, dtend = sanitize_timerange(
  File "/usr/lib/python3.10/site-packages/khal/icalendar.py", line 428, in sanitize_timerange
    if dtend < dtstart:
TypeError: can't compare datetime.datetime to datetime.date
```

[USHolidays.txt](https://github.com/pimutils/khal/files/9883691/USHolidays.txt)

**Comment by WhyNotHugo** [comment]
These events have a DTSTART of type DATE (e.g.: starts 2021-12-31) but a DTEND of type DATE-TIME (e.g.: ends 2021-12-31 05:00:01 UTC). It is my understanding that these are invalid; if the DTSTART is of type DATE, then DTEND must be of the same type.

Even if we somehow wanted to accept this input, it's a bit unclear how to fully interpret / render this.

All that said, we can definitely improve here, you should get a clear error on what's wrong rather than a crash with such a non-obvious error.
