### ISSUE TITLE
Exception on creation of Far-Future Date

### ISSUE THREAD

**Issue by willjp** [pimutils/khal#1200]
`khal-0.10.5`

I just stumbled on a minor bug, and thought you folks might want to know about it.
When creating a far-future event, khal raises an exception after successfully saving the event, when it tries to display the date of the event.

For example, I created an event 10 years in the future to remind myself to renew my passport.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1365, in start_pane
    loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.10/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
                                                                                                                                                                                     key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.10/site-packages/khal/ui/editor.py", line 544, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.10/site-packages/khal/ui/widgets.py", line 376, in keypress
    key = super().keypress(size, key)
  File "/usr/lib/python3.10/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.10/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/usr/lib/python3.10/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.10/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.10/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.10/site-packages/khal/ui/editor.py", line 526, in save
    self._save_callback(
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 733, in update_colors
    self.pane.calendar.original_widget.set_focus_date(new_start)
  File "/usr/lib/python3.10/site-packages/khal/ui/calendarwidget.py", line 660, in set_focus_date
    self.box.set_focus_date(a_day)
  File "/usr/lib/python3.10/site-packages/khal/ui/calendarwidget.py", line 312, in set_focus_date
    self.body.set_focus_date(a_day)
  File "/usr/lib/python3.10/site-packages/khal/ui/calendarwidget.py", line 388, in set_focus_date
    row, column = self.get_date_pos(a_day)
  File "/usr/lib/python3.10/site-packages/khal/ui/calendarwidget.py", line 436, in get_date_pos
    column = self[row].get_date_column(a_day)
IndexError: list index out of range
```

**Comment by mb720** [comment]
I tried creating an event two years in the future with `ikhal` 0.10.5-3 and got the same stack trace.

**Comment by mb720** [comment]
Thanks for working on this issue! 👍

I'm still on Arch Linux and what I did to install the current version, was:

    pip install git+https://github.com/pimutils/khal

This finished with:

>Successfully built khal
>Installing collected packages: khal
>Successfully installed khal-0.11.2.dev26+g9509967


    $ ikhal --version
    ikhal, version 0.11.2.dev26+g9509967

But running `ikhal` and creating an event two years from now produces this:

    Traceback (most recent call last):
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/__init__.py", line 1363, in start_pane
        loop.run()
      File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 320, in run
        self._run()
      File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 423, in _run
        self.event_loop.run()
      File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 148, in run
        self._loop()
      File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 189, in _loop
        self._watch_files[fd]()
      File "/usr/lib/python3.11/site-packages/urwid/raw_display.py", line 435, in <lambda>
        wrapper = lambda: self.parse_input(
                          ^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/raw_display.py", line 534, in parse_input
        callback(processed, processed_codes)
      File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 450, in _update
        self.process_input(keys)
      File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 548, in process_input
        k = self._topmost_widget.keypress(self.screen_size, k)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/wimp.py", line 678, in keypress
        return self._current_widget.keypress(size, key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/container.py", line 1612, in keypress
        return self.body.keypress( (maxcol, remaining), key )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/container.py", line 3069, in keypress
        key = w.keypress((mc,) + size[1:], key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/editor.py", line 554, in keypress
        return super().keypress(size, key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/widgets.py", line 381, in keypress
        key = super().keypress(size, key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/listbox.py", line 1058, in keypress
        key = focus_widget.keypress((maxcol,),key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/container.py", line 3069, in keypress
        key = w.keypress((mc,) + size[1:], key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/wimp.py", line 564, in keypress
        self._emit('click')
      File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 470, in _emit
        signals.emit_signal(self, name, self, *args)
      File "/usr/lib/python3.11/site-packages/urwid/signals.py", line 296, in emit
        result |= self._call_callback(callback, user_arg, weak_args, user_args, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/urwid/signals.py", line 320, in _call_callback
        return bool(callback(*args))
                    ^^^^^^^^^^^^^^^
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/editor.py", line 536, in save
        self._save_callback(
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/__init__.py", line 733, in update_colors
        self.pane.calendar.original_widget.set_focus_date(new_start)
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 654, in set_focus_date
        self.box.set_focus_date(a_day)
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 306, in set_focus_date
        self.body.set_focus_date(a_day)
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 382, in set_focus_date
        row, column = self.get_date_pos(a_day)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mb/.local/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 430, in get_date_pos
        column = self[row].get_date_column(a_day)
                ~~~~^^^^^
    IndexError: list index out of range

**Comment by geier** [comment]
@mb720 Sorry, I should have specified that: that PR isn't merged yet.

You can try to install it like this `pip install git+https://github.com/pimutils/khal.git@refs/pull/1262/head`

**Comment by mb720** [comment]
Most excellent! 👑

After running `pip install git+https://github.com/pimutils/khal.git@refs/pull/1262/head`, I can see with `ikhal --version` that I'm using 0.11.2.dev29+g8db5c2b.

I created a couple of events two years as well as ten years in the future and everything seems to work.
