### ISSUE TITLE
ModuleNotFoundError: xdg.BaseDirectory

### ISSUE THREAD

**Issue by hwanderer** [pimutils/khal#1206]
Hi,
since two days this error appears when trying to run khal:

---
Traceback (most recent call last):
  File "/usr/bin/khal", line 2, in <module>
    from khal.cli import main_khal
  File "/usr/lib/python3.10/site-packages/khal/cli.py", line 35, in <module>
    from .settings import InvalidSettingsError, get_config
  File "/usr/lib/python3.10/site-packages/khal/settings/__init__.py", line 2, in <module>
    from .settings import get_config  # noqa
  File "/usr/lib/python3.10/site-packages/khal/settings/settings.py", line 26, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
---

My installed xdg package is at v5.1.1

**Comment by d7415** [comment]
It may be worth checking you don't have another version of xdg installed with e.g. pip (see #959)
