### ISSUE TITLE
`ikhal` crashes with light theme

### ISSUE THREAD

**Issue by jasonccox** [pimutils/khal#1250]
Today I tried to launch `ikhal` and it crashed on me with the following trace:

```
Traceback (most recent call last):
  File "/usr/bin/ikhal", line 5, in <module>
    main_ikhal()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/cli.py", line 501, in interactive_cli
    controllers.interactive(
  File "/usr/lib/python3.11/site-packages/khal/controllers.py", line 593, in interactive
    ui.start_pane(
  File "/usr/lib/python3.11/site-packages/khal/ui/__init__.py", line 1328, in start_pane
    loop = urwid.MainLoop(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 127, in __init__
    screen.register_palette(palette)
  File "/usr/lib/python3.11/site-packages/urwid/display_common.py", line 989, in register_palette
    self.register_palette_entry(*item)
  File "/usr/lib/python3.11/site-packages/urwid/display_common.py", line 1070, in register_palette_entry
    mono = AttrSpec(mono, DEFAULT, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/display_common.py", line 554, in __init__
    raise AttrSpecError(
urwid.display_common.AttrSpecError: foreground/background ('dark cyan'/'default') require more colors than have been specified (1).
```

After a little trial and error, I discovered it was related to the light theme. More testing revealed that the problem was the [`today` element in the light theme colors](https://github.com/pimutils/khal/blob/acd62bc535feb2694636e6875397a471051fd2e4/khal/ui/colors.py#L72); removing the `dark cyan` at the end fixes the crash.

Running khal 0.11.1, Python 3.11.3. My package manager logs show the following recent updates that seem potentially relevant:

```
khal (0.10.5-3 -> 0.11.1-1)
python-atomicwrites (1.4.1-2 -> 1.4.1-3)
python-click (8.1.3-1 -> 8.1.3-3)
python-click-log (0.4.0-2 -> 0.4.0-3)
python-configobj (5.0.8-3 -> 5.0.8-4)
python-distro (1.8.0-2 -> 1.8.0-3)
python-pytz (2022.7.1-1 -> 2023.3-1)
python-icalendar (5.0.5-1 -> 5.0.5-2)
python-pyxdg (0.28-1 -> 0.28-2)
python-tzdata (2023.3-1 -> 2023.3-3)
python-pytz-deprecation-shim (0.1.0.post0-4 -> 0.1.0.post0-6)
python-tzlocal (1:4.3-1 -> 1:4.3-3)
python-urwid (2.1.2-3 -> 2.1.2.r55.gbac20db-1)
```

I don't understand khal's code, or the underlying urwid library that seems to be causing issues, well enough to know what the "right" fix for this is. I'm happy to submit a PR or file an issue with urwid if someone can point me in the right direction.

**Comment by yourealwaysbe** [comment]
Looking at the urwid docs/comments, the tuple entries for colors should have the "mono" value in position 3 (name, foreground, background, mono, ...). The  mono value should be one of 'bold', 'underline', 'blink', 'standout', 'strikethrough' (or empty i guess). "dark cyan" looks like a mistake that perhaps urwid silently ignored previously.

**Comment by geier** [comment]
I can't reproduce this, but I'm with @yourealwaysbe, that `dark cyan` does not belong there.
