### ISSUE TITLE
Can't import ics file

### ISSUE THREAD

**Issue by garyemiller** [pimutils/khal#1251]
I have a .ics file of USA Holidays, but it fails to import

[Hol.zip](https://github.com/pimutils/khal/files/11413308/Hol.zip)

Here is the failure:

````
kong /tmp # khal --verbosity DEBUG import Hol.ics 
debug: khal 0.11.1
debug: using the config file at /root/.config/khal/config
debug: discovering calendars in /root/.calendars/*
debug: found the following vdirs: ['/root/.calendars/4b7d37c7-ef1b-8e37-d66d-a588e4617fc8']
debug: Found no or empty file `color` in /root/.calendars/4b7d37c7-ef1b-8e37-d66d-a588e4617fc8
debug: Found no or empty file `displayname` in /root/.calendars/4b7d37c7-ef1b-8e37-d66d-a588e4617fc8
debug: discovering calendars in /root/.contacts/*
debug: found the following vdirs: ['/root/.contacts/a710428f-5e3d-cdac-b51f-8a48f7234454']
debug: Found no or empty file `color` in /root/.contacts/a710428f-5e3d-cdac-b51f-8a48f7234454
debug: Found no or empty file `displayname` in /root/.contacts/a710428f-5e3d-cdac-b51f-8a48f7234454
debug: Found no or empty file `color` in /root/.calendars/4b7d37c7-ef1b-8e37-d66d-a588e4617fc8
debug: Found no or empty file `color` in /root/.contacts/a710428f-5e3d-cdac-b51f-8a48f7234454
debug: Using config:
debug: [calendars]
debug:   [[4b7d37c7-ef1b-8e37-d66d-a588e4617fc8]]
debug:     path: /root/.calendars/4b7d37c7-ef1b-8e37-d66d-a588e4617fc8
debug:     color: None
debug:     type: calendar
debug:     readonly: False
debug:     priority: 10
debug:   [[a710428f-5e3d-cdac-b51f-8a48f7234454]]
debug:     path: /root/.contacts/a710428f-5e3d-cdac-b51f-8a48f7234454
debug:     color: None
debug:     type: calendar
debug:     readonly: False
debug:     priority: 10
debug: [locale]
debug:   timeformat: %H:%M
debug:   dateformat: %Y-%m-%d
debug:   longdateformat: %Y-%m-%d
debug:   datetimeformat: %Y-%m-%d %H:%M
debug:   longdatetimeformat: %Y-%m-%d %H:%M
debug:   firstweekday: 0
debug:   unicode_symbols: True
debug:   default_timezone: PST8PDT
debug:   local_timezone: PST8PDT
debug:   weeknumbers: False
debug: [default]
debug:   default_calendar: 4b7d37c7-ef1b-8e37-d66d-a588e4617fc8
debug:   timedelta: 31 days, 0:00:00
debug:   show_all_days: False
debug:   print_new: False
debug:   highlight_event_days: False
debug:   default_event_duration: 1 day, 0:00:00
debug:   default_dayevent_duration: 1:00:00
debug: [sqlite]
debug:   path: /root/.local/share/khal/khal.db
debug: [keybindings]
debug:   up: ['up', 'k']
debug:   down: ['down', 'j']
debug:   right: ['right', 'l', ' ']
debug:   left: ['left', 'h', 'backspace']
debug:   new: ['n']
debug:   delete: ['d']
debug:   view: ['enter']
debug:   external_edit: ['meta E']
debug:   today: ['t']
debug:   save: ['meta enter']
debug:   duplicate: ['p']
debug:   export: ['e']
debug:   mark: ['v']
debug:   other: ['o']
debug:   search: ['/']
debug:   log: ['L']
debug:   quit: ['q', 'Q']
debug: [view]
debug:   dynamic_days: True
debug:   event_view_weighting: 1
debug:   event_view_always_visible: False
debug:   blank_line_before_day: False
debug:   theme: dark
debug:   frame: False
debug:   bold_for_light_color: True
debug:   agenda_event_format: {calendar-color}{cancelled}{start-end-time-style} {title}{repeat-symbol}{alarm-symbol}{description-separator}{description}{reset}
debug:   agenda_day_format: {bold}{name}, {date-long}{reset}
debug:   monthdisplay: firstday
debug:   event_format: {calendar-color}{cancelled}{start}-{end} {title}{repeat-symbol}{alarm-symbol}{description-separator}{description}{reset}
debug: [highlight_days]
debug:   method: fg
debug:   color: 
debug:   multiple: 
debug:   multiple_on_overflow: False
debug:   default_color: 
debug: created version table
debug: tables for calendar 4b7d37c7-ef1b-8e37-d66d-a588e4617fc8 exist
debug: tables for calendar a710428f-5e3d-cdac-b51f-8a48f7234454 exist
can't compare datetime.datetime to datetime.date
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/khal/controllers.py", line 614, in import_ics
    vevents = split_ics(ics, random_uid, conf['locale']['default_timezone'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/icalendar.py", line 75, in split_ics
    return [ics_from_list(events, tzs, random_uid, default_timezone) for uid, events in
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/icalendar.py", line 75, in <listcomp>
    return [ics_from_list(events, tzs, random_uid, default_timezone) for uid, events in
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/icalendar.py", line 167, in ics_from_list
    sub_event = sanitize(sub_event, default_timezone=default_timezone)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/icalendar.py", line 395, in sanitize
    dtstart, dtend = sanitize_timerange(
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/icalendar.py", line 428, in sanitize_timerange
    if dtend < dtstart:
       ^^^^^^^^^^^^^^^
TypeError: can't compare datetime.datetime to datetime.date

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/khal/cli.py", line 464, in import_ics
    controllers.import_ics(
  File "/usr/lib/python3.11/site-packages/khal/controllers.py", line 616, in import_ics
    raise FatalError(error)
khal.exceptions.FatalError: can't compare datetime.datetime to datetime.date
critical: An error occurred when trying to import the file from Hol.ics
critical: Events from it will not be available in khal
````

**Comment by geier** [comment]
The issue seems to be, that at least the very first event in that ics file is invalid (DTSTART is a DATE, DTEND is a DATETIME), see:

```
BEGIN:VEVENT
UID:243379537850136179
LAST-MODIFIED:20201108T222755Z
DTSTART;VALUE=DATE:20210101
DTEND:20210101T050001Z
SUMMARY:New Year's Day
DESCRIPTION:New Years Day
CLASS:PUBLIC
DTSTAMP:20201115T134131Z
CATEGORIES:Holidays
RRULE:FREQ=YEARLY;BYMONTH=1;COUNT=10;BYMONTHDAY=1
END:VEVENT
```

I'll close this, as this is isn't really an issue with khal.

We could (should) think about the following:
* at nicer error messages (reason and which VEVENT is offending)
* offer to import non offending events from a file which contains some broken ones
* try to fix broken events
