### ISSUE TITLE
ikhal crashes when duplicating an event

### ISSUE THREAD

**Issue by Rostiger** [pimutils/khal#1265]
**Describe the bug**
ikhal crashes when duplicating an existing event.

**Stack Trace**
```
Traceback (most recent call last):
  File "/home/rostiger/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 1364, in start_pane
    loop.run()
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/rostiger/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 1124, in keypress
    return super().keypress(size, key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/khal/ui/base.py", line 114, in keypress
    return super().keypress(size, key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/khal/ui/widgets.py", line 313, in keypress
    key = super().keypress(size, key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/rostiger/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 915, in keypress
    self.duplicate()
  File "/home/rostiger/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 852, in duplicate
    self.pane.collection.new(event)
AttributeError: 'CalendarCollection' object has no attribute 'new'
```

**To Reproduce**
Run ikhal, select any event and press 'p'

**Expected behavior**
A duplicated event.

**OS, version, khal version and how you installed it:**
`Ubuntu 22.10 x86_64` 
`Python 3.10.7`
`khal version 0.11.1`
Installed using `pip3 install khal`

Config:
```
[calendars]

[[iCloud_local]]
path = ~/.calendars/iCloud/*
type = discover
color = light blue

[[google_local]]
path = ~/.calendars/google/*
type = discover

[default]
highlight_event_days = true
timedelta = 1d

[highlight_days]

[locale]
timeformat = %H:%M
dateformat = %y%m%d
longdateformat = %y%m%d
datetimeformat = %y%m%d %H:%M
longdatetimeformat = %Y-%m-%d %H:%M

[view]
agenda_day_format = "{reset}"
agenda_event_format = "{calendar-color}{start-end-time-style} {title} {location}{reset}"
frame = width
bold_for_light_color = false
dynamic_days = false
event_view_always_visible = true
```

**Comment by geier** [comment]
Thank you for reporting this! I believe we fixed this last week in https://github.com/pimutils/khal/pull/1260 (but haven't made a new release yet).

**Comment by geier** [comment]
new version released.

**Comment by Rostiger** [comment]
Fantastic, just downloaded the latest version and it's all fixed! Thanks!
