### ISSUE TITLE
install dev mode: ImportError: cannot import name '__productname__' from 'khal' (unknown location)

### ISSUE THREAD

**Issue by tgy** [pimutils/khal#1278]
I cloned this repo and then installed `khal` in dev mode in order to test my changes locally.

However I get an `ImportError`

```
~/p/khal pip install --no-deps -e .
Obtaining file:///home/v/p/khal
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: khal
  Building editable for khal (pyproject.toml) ... done
  Created wheel for khal: filename=khal-0.11.3.dev3+ge92d747.d20230623-0.editable-py3-none-any.whl size=7672 sha256=05ded7513a37d2f00789947360b00fea95caf52438e36a651b7e14ab9c525a9f
  Stored in directory: /tmp/pip-ephem-wheel-cache-0az2p1qw/wheels/81/7e/32/a00bca09d3e6b1471bdd363c88d9740613a29251cd2c3e61fc
Successfully built khal
Installing collected packages: khal
Successfully installed khal-0.11.3.dev3+ge92d747.d20230623
~/p/khal khal
Traceback (most recent call last):
  File "/home/v/micromamba/envs/val/bin/khal", line 5, in <module>
    from khal.cli import main_khal
  File "/home/v/p/khal/khal/cli.py", line 33, in <module>
    from . import __version__, controllers, khalendar
  File "/home/v/p/khal/khal/controllers.py", line 35, in <module>
    from khal import __productname__, __version__, calendar_display, parse_datetime, utils
ImportError: cannot import name '__productname__' from 'khal' (unknown location)
```

anything i'm doing wrong?

**Comment by geier** [comment]
I never used `--no-deps` can you try without that argument?

**Comment by tgy** [comment]
Thanks. This was not the issue. However, there was a weird remaining `khal` folder under `site-packages` in my environment (from a previous install) that was not properly deleted. Therefore it was resolving `khal` to this, which was mostly empty... Anyhow, closing!
