### ISSUE TITLE
google calendar sync issue

### ISSUE THREAD

**Issue by starenka** [pimutils/khal#18]
```
(tmp-28c39200d171d508)starenka /data/.envs/tmp-28c39200d171d508 % khal --sync                                                                                          [68% 05:33:08]
DEBUG:root:Using configuration::
DEBUG:root: accounts:
DEBUG:root:     google:
DEBUG:root:         auth: basic
DEBUG:root:         color: dark blue
DEBUG:root:         name: google
DEBUG:root:         readonly: False
DEBUG:root:         resource: https://www.google.com/calendar/dav/xxxx@gmail.com/user/
DEBUG:root:         server_type: caldav
DEBUG:root:         ssl_verify: False
DEBUG:root:         user: xxxx@gmail.com
DEBUG:root: debug: True
DEBUG:root: default:
DEBUG:root:     dateformat: %d.%m.
DEBUG:root:     datetimeformat: %d.%m. %H:%M
DEBUG:root:     debug: 1
DEBUG:root:     default_timezone: Europe/Prague
DEBUG:root:     encoding: utf-8
DEBUG:root:     firstweekday: 0
DEBUG:root:     local_timezone: Europe/Prague
DEBUG:root:     longdateformat: %d.%m.%Y
DEBUG:root:     longdatetimeformat: %d.%m.%Y %H:%M
DEBUG:root:     timeformat: %H:%M
DEBUG:root:     unicode_symbols: True
DEBUG:root: filename: /home/starenka/.config/khal/khal.conf
DEBUG:root: importing: None
DEBUG:root: list_accounts: False
DEBUG:root: new: None
DEBUG:root: sqlite:
DEBUG:root:     path: /home/starenka/.khal/khal.db
DEBUG:root: sync:
DEBUG:root:     accounts: set(['google'])
DEBUG:root: syncrun: True
DEBUG:root:created version table
DEBUG:root:created accounts table
DEBUG:root:starting to sync calendar `google`
DEBUG:root:syncing events in the next 365 days
DEBUG:root:Traceback (most recent call last):
File "/data/.envs/tmp-28c39200d171d508/local/lib/python2.7/site-packages/khal/khalendar.py", line 142, in sync
self._sync_caldav()
File "/data/.envs/tmp-28c39200d171d508/local/lib/python2.7/site-packages/khal/khalendar.py", line 164, in _sync_caldav
href_etag_list = syncer.get_hel(start=start_utc, end=end_utc)
File "/data/.envs/tmp-28c39200d171d508/local/lib/python2.7/site-packages/khal/caldav.py", line 235, in get_hel
etag = element.find('{DAV:}propstat').find('{DAV:}prop').find('{DAV:}getetag').text
AttributeError: 'NoneType' object has no attribute 'find'
```

contents of `response` was:

```
<?xml version="1.0" encoding="UTF-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:caldav="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:ical="http://apple.com/ns/ical/">
 <D:response xmlns:carddav="urn:ietf:params:xml:ns:carddav">
  <D:href>/calendar/dav/xxxxxx@gmail.com/user/</D:href>
  <D:propstat>
   <D:status>HTTP/1.1 200 OK</D:status>
  </D:propstat>
 </D:response>
</D:multistatus>
```

**Comment by ferenczy** [comment]
Sorry, for using this old and closed issue but what's meant by the "_not being part of khal anymore_", please? Does it mean that Google Calendar is not supported by khal?

**Comment by WhyNotHugo** [comment]
As stated above; use vdirsyncer for this.
