### ISSUE TITLE
Installed via pip on Ubuntu 14.04

### ISSUE THREAD

**Issue by GrouchyGaijin** [pimutils/khal#366]
I was able to install khal via pip, but when I try to launch khal I get:

```
Today is Tue Mar 01 @ 16:39:12 ~ $ khal
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 17, in <module>
    from requests.packages.urllib3 import connection
ImportError: No module named 'requests.packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/vdirsyncer/__init__.py", line 33, in _detect_faulty_requests
    from requests_toolbelt.auth.guess import GuessAuth  # noqa
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 22, in <module>
    from urllib3 import connection
ImportError: cannot import name 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/khal", line 7, in <module>
    from khal.cli import main_khal
  File "/usr/local/lib/python3.4/dist-packages/khal/cli.py", line 36, in <module>
    from khal import aux, controllers, khalendar, __version__
  File "/usr/local/lib/python3.4/dist-packages/khal/controllers.py", line 26, in <module>
    from vdirsyncer.utils.vobject import Item
  File "/usr/local/lib/python3.4/dist-packages/vdirsyncer/__init__.py", line 40, in <module>
    _detect_faulty_requests()
  File "/usr/local/lib/python3.4/dist-packages/vdirsyncer/__init__.py", line 36, in _detect_faulty_requests
    print(text.format(e=str(e), d=DOCS_HOME), file=sys.stderr)
```

**Comment by untitaker** [comment]
The output is missing some lines at the end.

**Comment by GrouchyGaijin** [comment]
OOPS - here it is again:

`Today is Tue Mar 01 @ 16:52:51 ~ $ khal
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 17, in <module>
    from requests.packages.urllib3 import connection
ImportError: No module named 'requests.packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/vdirsyncer/__init__.py", line 33, in _detect_faulty_requests
    from requests_toolbelt.auth.guess import GuessAuth  # noqa
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python3.4/dist-packages/requests_toolbelt/_compat.py", line 22, in <module>
    from urllib3 import connection
ImportError: cannot import name 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/khal", line 7, in <module>
    from khal.cli import main_khal
  File "/usr/local/lib/python3.4/dist-packages/khal/cli.py", line 36, in <module>
    from khal import aux, controllers, khalendar, __version__
  File "/usr/local/lib/python3.4/dist-packages/khal/controllers.py", line 26, in <module>
    from vdirsyncer.utils.vobject import Item
  File "/usr/local/lib/python3.4/dist-packages/vdirsyncer/__init__.py", line 40, in <module>
    _detect_faulty_requests()
  File "/usr/local/lib/python3.4/dist-packages/vdirsyncer/__init__.py", line 36, in _detect_faulty_requests
    print(text.format(e=str(e), d=DOCS_HOME), file=sys.stderr)
NameError: name 'DOCS_HOME' is not defined
Today is Tue Mar 01 @ 16:52:54 ~ $ 
`

**Comment by untitaker** [comment]
So, the error message should be fixed in vdirsyncer... however, you still have a broken version of requests installed. The problem and workarounds are described at https://vdirsyncer.readthedocs.org/en/stable/problems.html#requests-related-importerrors-on-debian-based-distributions

**Comment by untitaker** [comment]
@GrouchyGaijin Any update on this?

**Comment by GrouchyGaijin** [comment]
I have not had time to try this again.

**Comment by untitaker** [comment]
`vdirsyncer` is now a proper debian package, please try that.

**Comment by geier** [comment]
closed for lack of activity, please reopen if you are still interested in this.
