### ISSUE TITLE
Troublesome ical file from Google calendar crashes khal.

### ISSUE THREAD

**Issue by lucc** [pimutils/khal#372]
I have downloaded a ical file from a google calendar that crashes khal. I can not see any problem with the file as the only [validator](http://severinghaus.org/projects/icv/) I could find online says it's alright and I myself don't understand ical.

My config:
```
[default]
  default_calendar = test
[calendars]
  [[test]]
    path = ~/tmp/khal_test
```
There is only this one file in ~/tmp/khal_test:
```ical
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Jongliertreffen
X-WR-TIMEZONE:Europe/Berlin
X-WR-CALDESC:
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20160324T180000
DTEND;TZID=Europe/Berlin:20160324T200000
DTSTAMP:20160226T095239Z
UID:gufv2ho7nnn976vmv2v4jfffkk@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Jongli
 ertreffen;X-NUM-GUESTS=0:mailto:jimev.de_m3bmcm2sr1r02s3d8nn7bfcg9o@group.c
 alendar.google.com
RECURRENCE-ID;TZID=Europe/Berlin:20160324T180000
CREATED:20120628T032825Z
DESCRIPTION:Wir freuen uns auf euren Besuch. Einfach mal vorbeikommen und K
 ontakte knüpfen. Die Hallenzeit wird von JIM e.V. organisiert.\n<a href="ht
 tp://www.jimev.de/index.php?site=1109">weitere Infos</a>
LAST-MODIFIED:20160120T134132Z
LOCATION:Schlierseestr. 20\, München
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:Asam-Gymnasium
TRANSP:OPAQUE
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```
The stack trace:
```
Traceback (most recent call last):
  File "/usr/bin/khal", line 9, in <module>
    load_entry_point('khal==0.7.1.dev177+ngacc28ab.d20160309', 'console_scripts', 'khal')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/khal/cli.py", line 292, in agenda
    bold_for_light_color=ctx.obj['conf']['view']['bold_for_light_color']
  File "/usr/lib/python3.5/site-packages/khal/controllers.py", line 168, in agenda
    bold_for_light_color=bold_for_light_color, **kwargs)
  File "/usr/lib/python3.5/site-packages/khal/controllers.py", line 116, in get_agenda
    items = event.relative_to(day, full).splitlines()
  File "/usr/lib/python3.5/site-packages/khal/khalendar/event.py", line 414, in relative_to
    body = self.summary
  File "/usr/lib/python3.5/site-packages/khal/khalendar/event.py", line 343, in summary
    bday = self._vevents[self.ref].get('x-birthday', None)
KeyError: '1458838800'
```

**Comment by geier** [comment]
Thanks for reporting this and illustrating that this (#323) is indeed a pressing issue, still not really sure how to handle that.
