### ISSUE TITLE
warning: unknown exception for birthdays when starting khal

### ISSUE THREAD

**Issue by lecagot** [pimutils/khal#390]
When starting khal first time after boot (? at least it doesn't happen after starting it again) it throws warnings for the birthdays (synced with khard/vdirsyncer):

```bash
$ khal --version
  khal, version 0.7.1.dev122+ngf4059cd.d20160216
```

```python
[..]
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 286, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 309, in update_birthday
    self.sql_ex(sql_s, stuple)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 215, in sql_ex
    self.cursor.execute(statement, stuple)
sqlite3.IntegrityError: UNIQUE constraint failed: events.href, events.calendar
warning: Skipping birthdays/bdd34d56-ed14-445a-aa32-d0ccc1ca446f.vcf: UNIQUE constraint failed: events.hre
warning: This event will not be available in khal.
[..]
```

However khal displays all birthday events correctly. So I am unsure what this means.

----

* Birthdays settings in config:

```ini
[calendars]
[[birthdays]]
path = ~/.contacts/
color = brown
type = birthdays
```

* `.contacts/bdd34d56-ed14-445a-aa32-d0ccc1ca446f.vcf`

```
BEGIN:VCARD
VERSION:3.0
UID:bdd34d56-ed14-445a-aa32-d0ccc1ca446f
PRODID:+//IDN bitfire.at//DAVdroid/0.9.1.3 vcard4android ez-vcard/0.9.8
FN:First Last
N:Last;First;;;
BDAY:1889-02-21
REV:20160325T110319Z
X-RADICALE-NAME:bdd34d56-ed14-445a-aa32-d0ccc1ca446f.vcf
END:VCARD
```

**Comment by untitaker** [comment]
Could you grep your contacts directory for `bdd34d56-ed14-445a-aa32-d0ccc1ca446f`?

**Comment by lecagot** [comment]
file(s) is(/are) present, yes:

```bash
$ ls ~/.contacts/ | grep bdd34d56-ed14-445a-aa32-d0ccc1ca446f
-rw------- 1 user user 411 Mar 25 12:30 bdd34d56-ed14-445a-aa32-d0ccc1ca446f.vcf
```

or do I misunderstand you?

**Comment by geier** [comment]
Can you try to delete the db file, run khal again and see if the error persists?

**Comment by lecagot** [comment]
yeah, this fixed it. thanks!
