### ISSUE TITLE
ikhal: crash if turning an allday event to non-allday and changing the hours

### ISSUE THREAD

**Issue by legrostdg** [pimutils/khal#404]
In ikhal, the following steps make the program crash:

- creating an allday event
- saving it
- editing it
- turning it non-allday
- editing one of the hours
- moving the cursor to edit the other hour

The error is:

    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/__init__.py", line 924, in start_pane
        loop.run()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
        self._run()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
        self.event_loop.run()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 682, in run
        self._loop()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 719, in _loop
        self._watch_files[fd]()
      File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
        event_loop, callback, self.get_available_raw_input())
      File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
        callback(processed, processed_codes)
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
        self.process_input(keys)
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
        k = self._topmost_widget.keypress(self.screen_size, k)
      File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
        return self._current_widget.keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
        return self.body.keypress( (maxcol, remaining), key )
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
        key = w.keypress((mc,) + size[1:], key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/__init__.py", line 662, in keypress
        return super().keypress(size, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/widgets.py", line 370, in keypress
        key = super().keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 985, in keypress
        key = focus_widget.keypress((maxcol,),key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/startendeditor.py", line 102, in keypress
        return super().keypress(size, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/widgets.py", line 302, in keypress
        key = super(NextMixin, self).keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
        key = self.focus.keypress(tsize, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/widgets.py", line 302, in keypress
        key = super(NextMixin, self).keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
        key = w.keypress((mc,) + size[1:], key)
      File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
        return self._original_widget.keypress(maxvals, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/widgets.py", line 428, in keypress
        if not self._validate():
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/widgets.py", line 402, in _validate
        if self._validate_func(text):
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev19+ngae2d4a7-py3.5.egg/khal/ui/startendeditor.py", line 169, in _validate_end_time
        self._enddt = self.localize_end(datetime.combine(self._enddt.date(), endval.time()))
    AttributeError: 'datetime.date' object has no attribute 'date'

**Comment by geier** [comment]
Thank you for reporting this bug. It looks like a regression caused by
my refactoring yesterday. You can probably use the last released version
until I fixed this.

Quoting legrostdg (2016-04-19 17:56:02)

**Comment by geier** [comment]
I believe I have this fixed, please reopen if this isn't the case.

**Comment by legrostdg** [comment]
It seems to be fixed, thanks!
