### ISSUE TITLE
ikhal: crashes if creating a new event, going to the date, pressing enter

### ISSUE THREAD

**Issue by legrostdg** [pimutils/khal#405]
If I create a new event, go to modify the date, press "enter", ikhal crashes.

    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/__init__.py", line 924, in start_pane
        loop.run()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
        self._run()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
        self.event_loop.run()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 682, in run
        self._loop()
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 719, in _loop
        self._watch_files[fd]()
      File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
        event_loop, callback, self.get_available_raw_input())
      File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
        callback(processed, processed_codes)
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
        self.process_input(keys)
      File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
        k = self._topmost_widget.keypress(self.screen_size, k)
      File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
        return self._current_widget.keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
        return self.body.keypress( (maxcol, remaining), key )
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
        key = w.keypress((mc,) + size[1:], key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/__init__.py", line 662, in keypress
        return super().keypress(size, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/widgets.py", line 370, in keypress
        key = super().keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 985, in keypress
        key = focus_widget.keypress((maxcol,),key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/startendeditor.py", line 102, in keypress
        return super().keypress(size, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/widgets.py", line 302, in keypress
        key = super(NextMixin, self).keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
        key = self.focus.keypress(tsize, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/widgets.py", line 302, in keypress
        key = super(NextMixin, self).keypress(size, key)
      File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
        key = w.keypress((mc,) + size[1:], key)
      File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
        return self._original_widget.keypress(maxvals, key)
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/startendeditor.py", line 52, in keypress
        self.open_pop_up()
      File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 586, in open_pop_up
        self._pop_up_widget = self.create_pop_up()
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/startendeditor.py", line 68, in create_pop_up
        initial=self.base_widget._get_current_value())
      File "/home/user/.local/lib/python3.5/site-packages/khal-0.8.2.dev20+ngd64a1e3-py3.5.egg/khal/ui/calendarwidget.py", line 607, in __init__
        self.set_focus_date(self._initial)
    AttributeError: 'CalendarWidget' object has no attribute '_initial'

**Comment by geier** [comment]
Thank you for reporting this bug, I'll try to take care of it ASAP (and will finally write some tests for StartEndEditor).
