### ISSUE TITLE
khal (0.8.1) barfs and dies on config if ~/.config/khal doesn't exist

### ISSUE THREAD

**Issue by waynew** [pimutils/khal#415]
Running Arch linux with the latest python (3.5) and `python -m pip install --user khal`, when I ran `khal configure` and went through the config:

```
Do you want to write the config to /home/wayne/.config/khal/khal.conf? (Choosing `No` will abort) [y/N]: y
Traceback (most recent call last):
  File "/home/wayne/.local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/home/wayne/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/wayne/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/wayne/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wayne/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wayne/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/wayne/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/wayne/.local/lib/python3.5/site-packages/khal/cli.py", line 496, in configure
    configwizard.configwizard()
  File "/home/wayne/.local/lib/python3.5/site-packages/khal/configwizard.py", line 188, in configwizard
    with open(config_path, 'w') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wayne/.config/khal/khal.conf'
```

doing `mkdir -p ~/.config/khal` and then re-running config worked fine.

I suspect the correct action here would be something like `makedirs(os.path.dirname(config_path), exist_ok=True)` before opening the `config_file`

**Comment by geier** [comment]
Should be fixed with the latest release, please reopen (or comment) if anyone gets the same bug.
