### ISSUE TITLE
Khal wont run on latest Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by hsanson** [pimutils/khal#445]
With khal installed via pip with:

    pip install --user khal

it fails to run:

```python
> khal
Traceback (most recent call last):
  File "/home/ryujin/.local/bin/khal", line 7, in <module>
    from khal.cli import main_khal
  File "/home/ryujin/.local/lib/python2.7/site-packages/khal/cli.py", line 25, in <module>
    from shutil import get_terminal_size
ImportError: cannot import name get_terminal_size
```

**Comment by geier** [comment]
khal doesn't work with python 2 anymore, you could try to use `pip3` or
even better, use pipsi.


Quoting Horacio Sanson (2016-06-16 16:18:38)

**Comment by hsanson** [comment]
Using pip3 works perfect.
