### ISSUE TITLE
self tests report weird error

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/khal#464]
`python3.5 setup.py test` gives me:
````
running test
running egg_info
writing requirements to khal.egg-info/requires.txt
writing khal.egg-info/PKG-INFO
writing top-level names to khal.egg-info/top_level.txt
writing entry points to khal.egg-info/entry_points.txt
writing dependency_links to khal.egg-info/dependency_links.txt
reading manifest file 'khal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'khal.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    "Topic :: Communications",
  File "/usr/pkg/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/pkg/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/pkg/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/pkg/lib/python3.5/site-packages/setuptools/command/test.py", line 172, in run
    self.run_tests()
  File "/usr/pkg/lib/python3.5/site-packages/setuptools/command/test.py", line 193, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/pkg/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/pkg/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/usr/pkg/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/pkg/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/pkg/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/pkg/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/pkg/lib/python3.5/site-packages/setuptools/command/test.py", line 40, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/pkg/lib/python3.5/unittest/loader.py", line 213, in loadTestsFromName
    raise TypeError("don't know how to make test from: %s" % obj)
TypeError: don't know how to make test from: 0.8.2
*** Error code 1

````

**Comment by youngmoney** [comment]
I believe tests aren't set up through setup.py

If you install py-test then in the khal repo you can run `py.test tests` (there might be a dependency on freezegun for date freezing)

**Comment by 0-wiz-0** [comment]
Fair enough. Looking more for it I see that this is even mentioned in `CONTRIBUTING.txt`. I'll close this and open one with for the test failures ;-)
