### ISSUE TITLE
RECURRENCE-ID but no "master" event

### ISSUE THREAD

**Issue by rxcomm** [pimutils/khal#497]
"khal agenda" works, but "khal agenda --days 7" doesn't.

```
$ khal agenda --days 7
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/khal/cli.py", line 303, in agenda
    bold_for_light_color=ctx.obj['conf']['view']['bold_for_light_color']
  File "/usr/local/lib/python3.5/dist-packages/khal/controllers.py", line 175, in agenda
    bold_for_light_color=bold_for_light_color, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/khal/controllers.py", line 121, in get_agenda
    items = event.relative_to(day, full).splitlines()
  File "/usr/local/lib/python3.5/dist-packages/khal/khalendar/event.py", line 448, in relative_to
    body = self.summary
  File "/usr/local/lib/python3.5/dist-packages/khal/khalendar/event.py", line 343, in summary
    bday = self._vevents[self.ref].get('x-birthday', None)
KeyError: '1473107400'
```

**Comment by youngmoney** [comment]
Seems like a particular event is having a problem, try wrapping line 121 in controllers.py with a try catch, and in the catch print the event.href 

I believe this should give you the offending event, perhaps posting it here would be helpful too (feel free to clean out any sensitive info)

**Comment by rxcomm** [comment]
Here's the event:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CALENDARSERVER.ORG//NONSGML Version 1//EN
BEGIN:VEVENT
SUMMARY;LANGUAGE=en-US:Canceled: xxx
DTSTART;TZID="Central Standard Time":20160905T153000
DTEND;TZID="Central Standard Time":20160905T163000
DTSTAMP:20160830T163903Z
UID:040000008200E00074C5B7101A82E0080000000060AD130A50FCD10100000000000000
 0010000000DD20BCEA2C0D7241A4EF4172790B088C
RECURRENCE-ID;TZID="Central Standard Time":20160905T153000
SEQUENCE:3
ATTENDEE;CN="xxx";PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT
 ;RSVP=TRUE:MAILTO:xxx@xxx.xxx
ATTENDEE;CN="xxx";PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:MAILTO:xxx
ATTENDEE;CN="xxx";PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;
 RSVP=TRUE:MAILTO:xxx@xxx.xxx
ATTENDEE;CN="xxx";PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;RS
 VP=TRUE:MAILTO:xxx@xxx.xxx
ATTENDEE;CN="xxx";PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;RSV
 P=TRUE:MAILTO:xxx@xxx.xxx
ATTENDEE;CN="xxx";PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPAN
 T;RSVP=TRUE:MAILTO:xxx@xxx.xxx
CLASS:PUBLIC
DESCRIPTION;LANGUAGE=en-US:When: Monday\, September 05\, 2016 3:30 PM-4:30
  PM (UTC-06:00) Central Time (US & Canada).\nWhere: 3210 SC\n\nNote: The G
 MT offset above does not reflect daylight saving time adjustments.\n\n*~*~
 *~*~*~*~*~*~*~*\n\nCanceling this meeting which falls on Labor Day\n\n
LOCATION;LANGUAGE=en-US:xxx
ORGANIZER;CN=RES-SC3210;SENT-BY="xxx@xxx.xxx":MAILTO:xxx@xxx.xxx
PRIORITY:1
STATUS:CANCELLED
TRANSP:OPAQUE
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-APPT-SEQUENCE:3
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-IMPORTANCE:2
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-CDO-INTENDEDSTATUS:FREE
X-MICROSOFT-CDO-OWNERAPPTID:-141129760
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```

**Comment by geier** [comment]
The problem seems to be the following: this event is only the exception to a repeating event, but the "original" event is not included in here. Could you `grep` through this event's vdir for its UID, or better only the first line of it (`UID:040000008200E00074C5B7101A82E0080000000060AD130A50FCD10100000000000000`) and see if you have any other events matching that?

Also, which vdirsyncer version did you use?

(reminder to myself: check #376 and references therein)

**Comment by geier** [comment]
Is there any update on this?

**Comment by geier** [comment]
closing for lack of response, please reopen (or file a new issue) if this issue persists.
