### ISSUE TITLE
tests do not run on python 3.6

### ISSUE THREAD

**Issue by geier** [pimutils/khal#556]
see #547

**Comment by geier** [comment]
can be reproduced by setting system timezone to UTC. this is gonna be one fun one.

**Comment by geier** [comment]
```python
import datetime as dt
import pytz
import sys

print(sys.version_info)

BERLIN = pytz.timezone('Europe/Berlin')
now = dt.datetime.now()
now.astimezone(BERLIN)
```
```
$ python2.7 test2.py
sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "test2.py", line 9, in <module>
    now.astimezone(BERLIN)
ValueError: astimezone() cannot be applied to a naive datetime
```
```
$ python3.5 test2.py
sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "test2.py", line 9, in <module>
    now.astimezone(BERLIN)
ValueError: astimezone() cannot be applied to a naive datetime
```
```
$ python3.6 test2.py	
sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```


Arrrg. Another instance of "asking for forgiveness" coming back to bite me.

**Comment by hobarrera** [comment]
> Changed in version 3.6: The astimezone() method can now be called on naive instances that are presumed to represent system local time.

Source: https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone

**Comment by geier** [comment]
Thanks for finding that.
