### ISSUE TITLE
AttributeError: 'Etc/UTC' object has no attribute '_tzinfos'

### ISSUE THREAD

**Issue by waynew** [pimutils/khal#557]
The timezone on my server is set to UTC. I added an appointment with ikhal, and when I quit it barfed with this stacktrace:

```
Traceback (most recent call last):
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/ui/__init__.py", line 1402, in start_pane
    loop.run()
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/ui/__init__.py", line 1063, in keypress
    return super().keypress(size, key)
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/ui/widgets.py", line 370, in keypress
    key = super().keypress(size, key)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/home/wayne/.local/lib/python3.6/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/ui/__init__.py", line 1036, in save
    self.collection.new(self.event)
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 205, in new
    event.href, event.etag = self._storages[calendar].upload(event)
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/khalendar/vdir.py", line 207, in upload
    if not isinstance(item.raw, str):
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/khalendar/event.py", line 330, in raw
    timezone = create_timezone(tzinfo, self.start)
  File "/home/wayne/.local/lib/python3.6/site-packages/khal/khalendar/event.py", line 716, in create_timezone
    for one, two in iter(tz._tzinfos.items())
AttributeError: 'Etc/UTC' object has no attribute '_tzinfos'
```

**Comment by geier** [comment]
this looks like a bug.

**Comment by geier** [comment]
I'd suggest a workaround of setting [locale] local_timezone and default_timezone to "UTC".

This is obviously a valid bug, I'll close it anyway and point everybody to #558, where I have collected some more information on this bug.
