### ISSUE TITLE
`list --notstarted' breaks with present AllDayEvent

### ISSUE THREAD

**Issue by terlar** [pimutils/khal#578]
Currently khal list includes all day events, but when used together with the `--notstarted` option it doesn't take into account that the `AllDayEvent` object doesn't have the `event_start` attribute.

```
$ khal list --notstarted
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.2', 'console_scripts', 'khal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 320, in klist
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 263, in khal_list
    **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 179, in get_list_from_str
    **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 226, in get_list
    if not (notstarted and event.event_start.replace(tzinfo=None) < start):
AttributeError: 'AllDayEvent' object has no attribute 'event_start'
```

**Comment by geier** [comment]
Should be fixed with the above mentioned commit. Thanks for reporting this.

**Comment by terlar** [comment]
Thanks for the quick fix, and nice to see you added some regression tests.

**Comment by geier** [comment]
always at least try to, I really hate to see the same bug twice...
