### ISSUE TITLE
Configuration wizard crashes if you answer no to "Do you want to create a local calendar?"

### ISSUE THREAD

**Issue by mortie** [pimutils/khal#579]
In both 0.9.2 and the most recent master version, when running `khal configure` and answering no to "Do you want to create a local calendar?", khal crashes. The full stack trace:

```
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.2', 'console_scripts', 'khal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal-0.9.2-py3.6.egg/khal/cli.py", line 609, in configure
    configwizard.configwizard()
  File "/usr/lib/python3.6/site-packages/khal-0.9.2-py3.6.egg/khal/configwizard.py", line 193, in configwizard
    config = create_config(vdirs, dateformat=dateformat, timeformat=timeformat)
  File "/usr/lib/python3.6/site-packages/khal-0.9.2-py3.6.egg/khal/configwizard.py", line 154, in create_config
    for name, path, type_ in sorted(vdirs) or ():
TypeError: 'NoneType' object is not iterable
```

The issue seems to be that on line 154 in configwizard.py, you're trying to iterate over vdirs if they exist, and they only exist if you either have a previous vdirsyncer config (I think) or you allowed it to create a new private calendar.

The for loop looks like this: `for whatever in sorted(vdirs) or ()`, which doesn't work, because `sorted(None)` produces the `TypeError: 'NoneType' object is not iterable` error.

**Comment by geier** [comment]
should be fixed with the above mentioned commit. Thank your for reporting this.
