### ISSUE TITLE
edit without arguments / some events get invalid `tzinfo' to `replace'

### ISSUE THREAD

**Issue by terlar** [pimutils/khal#581]
```
$ khal edit                                                                                                                                       (0.71s)
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.3.dev13+ngeb15f17.d20170219', 'console_scripts', 'khal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 570, in edit
    conf=ctx.obj['conf']
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 483, in edit
    end = event.end_local.replace(tzinfo=None)
TypeError: 'tzinfo' is an invalid keyword argument for this function
```

Since the edit has the description "Interactively edit (or delete) events..." my first thought was to just run `khal edit` and then I was met by this output.

When I checked the help for the edit command itself I saw that it took a search string, and then the command worked, so I guess it is event-related. Seems this specific line would never work though right?

**Comment by geier** [comment]
Thanks for reporting this, should be fixed now.
