### ISSUE TITLE
After importing an event, khal won't start anymore

### ISSUE THREAD

**Issue by edi9999** [pimutils/khal#593]
The stacktrace is : 

```
Traceback (most recent call last):
  File "/home/edgar/.local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/home/edgar/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/edgar/.local/lib/python3.5/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/edgar/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/edgar/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/cli.py", line 250, in cli
    ctx.invoke(cli.commands[command])
  File "/home/edgar/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/cli.py", line 286, in calendar
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/controllers.py", line 105, in calendar
    **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/controllers.py", line 186, in get_list_from_str
    end=day_end, notstarted=notstarted, env=env, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/controllers.py", line 228, in get_list
    events = sorted(collection.get_localized(start_local, end_local))
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 147,in <genexpr>
    return (self._cover_event(event) for event in events)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/khalendar/backend.py", line 485, in get_localized
    yield self.construct_event(item, href, start, end, ref, etag, calendar, dtype)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/khalendar/backend.py", line 564, in construct_event
    ref=ref,
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/khalendar/event.py", line 150, in fromString
    return cls.fromVEvents(events, ref, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/khalendar/event.py", line 144, in fromVEvents
    return instcls(vevents, ref=ref, **kwargs)
  File "/home/edgar/.local/lib/python3.5/site-packages/khal/khalendar/event.py", line 615, in __init__
    starttz = getattr(self._vevents[self.ref]['DTSTART'].dt, 'tzinfo', None)
KeyError: '1487770200'
```

**Comment by geier** [comment]
Thank you for reporting this, I need to see the event that causes this though. I just pushed a change that should improve logging, in case you installed from git, please pull the latest changes and then paste the failing event (feel free to remove any private information, just leave the structure of the event in tact).

Most likely case, this is a case of https://github.com/pimutils/khal/issues/447.

**Comment by geier** [comment]
any updates on this?

**Comment by edi9999** [comment]
I haven't seen the issue for a while, and I don't know how to reproduce it.

I will reopen if I encounter it again.
