### ISSUE TITLE
khal crashes when starting with `list --notstarted`

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/khal#595]
Version: `khal, version 0.9.2`

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.2', 'console_scripts', 'khal')()
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/cli.py", line 320, in klist
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/controllers.py", line 263, in khal_list
    **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/controllers.py", line 179, in get_list_from_str
    **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/controllers.py", line 226, in get_list
    if not (notstarted and event.event_start.replace(tzinfo=None) < start):
AttributeError: 'LocalizedEvent' object has no attribute 'event_start'
```

The command `khal list today` works successfully, so it handles the events fine as long as it isn't checking the start time.

**Comment by samdmarshall** [comment]
Updating this as i was able to repro it in another circumstance: 

```
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.2', 'console_scripts', 'khal')()
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/cli.py", line 320, in klist
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/controllers.py", line 263, in khal_list
    **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/controllers.py", line 179, in get_list_from_str
    **kwargs)
  File "/usr/local/Cellar/khal/0.9.2/libexec/lib/python3.6/site-packages/khal/controllers.py", line 226, in get_list
    if not (notstarted and event.event_start.replace(tzinfo=None) < start):
AttributeError: 'AllDayEvent' object has no attribute 'event_start'
```

**Comment by geier** [comment]
I believe this bug is fixed in master, it would be great if you could check that.

But I'm going to make a new release really soon either way.

**Comment by samdmarshall** [comment]
This seems to be fixed on master, i'm not encountering the crash again, but since the day in question is in the past and it may have been event-specific data causing it.  I will give it a go again once the new release comes out and keep an eye out for it happening.

**Comment by geier** [comment]
thank you!
