### ISSUE TITLE
interactive new event gives ERROR

### ISSUE THREAD

**Issue by doronbehar** [pimutils/khal#620]
I just checked that I have the latest version of `khal` and I ran:
`khal new --interactive` and got the following traceback:
```
Traceback (most recent call last):
  File "/home/doron/.local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/khal/cli.py", line 396, in new
    format=format,
  File "/home/doron/.virtualenv/khal/lib/python3.6/site-packages/khal/controllers.py", line 280, in new_interactive
    info, conf['locale'], default_timedelta="60m", adjust_reasonably=True, localize=False)
TypeError: eventinfofstr() got an unexpected keyword argument 'default_timedelta'
```

**Comment by geier** [comment]
Thank you for reporting this, I believe I fixed it with the above mentioned commit. If this is not the case, please re-open/file a new issue.

**Comment by doronbehar** [comment]
It's fixed in the latest development version install-able with `pip install git+git://github.com/pimutils/khal.git`. Perhaps the stable version should be updated as well..
