### ISSUE TITLE
_extract_offsets: 'rrule._until' has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by in0rdr** [pimutils/khal#672]
Decided to switch from KOrganizer to Khal again (I used khal before with this same calendar/ics file). Had to do a `vdirsyncer repair my_calendar_remote/calendar` beause of some duplicates.

Should work now, all duplicates removed but every calendar entry khal tries to read gives the following error msg:
```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/khal-0.9.6.dev53+g43f4c71-py3.5.egg/khal/khalendar/khalendar.py", line 303, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/local/lib/python3.5/dist-packages/khal-0.9.6.dev53+g43f4c71-py3.5.egg/khal/khalendar/backend.py", line 228, in update
    ical = icalendar.Event.from_ical(vevent_str)
  File "/usr/local/lib/python3.5/dist-packages/icalendar/cal.py", line 369, in from_ical
    _timezone_cache[component['TZID']] = component.to_tz()
  File "/usr/local/lib/python3.5/dist-packages/icalendar/cal.py", line 588, in to_tz
    component, tzname
  File "/usr/local/lib/python3.5/dist-packages/icalendar/cal.py", line 546, in _extract_offsets
    elif rrule._until.tzinfo:
AttributeError: 'NoneType' object has no attribute 'tzinfo'
warning: Skipping calendar/a180a5c0-d94a-450d-b035-ffeea119e79b.ics: 'NoneType' object has no attribute 'tzinfo'
warning: This event will not be available in khal.
```
There seems to be something wrong with my formatting of the events (coming from KOrganizer), more precisely the timezone part. This is the mentioned event corresponding to the error msg above:
```
BEGIN:VEVENT
DTSTAMP:20170302T112452Z
X-MOZ-GENERATION:1
X-MOZ-LASTACK:20160611T194959Z
X-RADICALE-NAME:a180a5c0-d94a-450d-b035-ffeea119e79b.ics
CREATED:20170224T123957Z
UID:a180a5c0-d94a-450d-b035-ffeea119e79b
LAST-MODIFIED:20170302T112452Z
SUMMARY:Summary
STATUS:CONFIRMED
DTSTART;TZID=Europe/Zurich:20160610T170000
DTEND;TZID=Europe/Zurich:20160610T180000
TRANSP:OPAQUE
BEGIN:VALARM
DESCRIPTION:Description
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT10M
X-KDE-KCALCORE-ENABLED:TRUE
X-RADICALE-NAME:a180a5c0-d94a-450d-b035-ffeea119e79b.ics
END:VALARM
END:VEVENT
```

I'm surprised of the error msg, because this was not a recurring event, but I have some other recurring events in the same ics file. Those I created with KOrganizer.

I am using khal, version `0.9.6.dev53+g43f4c71`. I sync with the radicale server and also have Davdroid on my phone.

Thanks

**Comment by geier** [comment]
That's unfortunate.

Because the error occurs when `icalendar.Event.from_ical(vevent_str)` is called, I'm pretty sure this is an icalendar issue. As I have written that VTIMEZONE handling code, you'll meet me there as well and we can at least triage the issue here.

Can you post the VTIMEZONE part of one of those events please? Also, what version of icalendar are you using? (`python -c 'import icalendar; print(icalendar.__version__)'`, or, if that fails, `pip freeze | grep icalendar`) Thanks

**Comment by in0rdr** [comment]
Ah now I see, it's an icalendar thing. Should I move the issue over there?

The VTIMEZONE for the event mentioned above is:
```
BEGIN:VTIMEZONE
TZID:Europe/Zurich
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+002946
TZOFFSETTO:+0100
DTSTART:19011213T211538
RDATE;VALUE=DATE-TIME:19011213T211538
X-RADICALE-NAME:Europe/Zurich
END:STANDARD
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
X-RADICALE-NAME:Europe/Zurich
END:DAYLIGHT
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19410505T010000
RDATE;VALUE=DATE-TIME:19410505T010000
RDATE;VALUE=DATE-TIME:19420504T010000
X-RADICALE-NAME:Europe/Zurich
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19810927T030000
RRULE:FREQ=YEARLY;COUNT=15;BYDAY=-1SU;BYMONTH=9
X-RADICALE-NAME:Europe/Zurich
END:STANDARD
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
X-RADICALE-NAME:Europe/Zurich
END:STANDARD
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19411006T020000
RDATE;VALUE=DATE-TIME:19411006T020000
RDATE;VALUE=DATE-TIME:19421005T020000
X-RADICALE-NAME:Europe/Zurich
END:STANDARD
X-RADICALE-NAME:Europe/Zurich
END:VTIMEZONE
```

I am using icalendar version `3.11.4`
Thanks

**Comment by geier** [comment]
I can't reproduce this at my end.

Could you try running the following script:

```python
import icalendar                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                
event_str = """BEGIN:VCALENDAR                                                                                                                                                                                                                                                                                                                                                                                                  
BEGIN:VTIMEZONE                                                                                                                                                                                                                                                                                                                                                                                                                 
TZID:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                              
BEGIN:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                  
TZNAME:CET                                                                                                                                                                                                                                                                                                                                                                                                                      
TZOFFSETFROM:+002946                                                                                                                                                                                                                                                                                                                                                                                                            
TZOFFSETTO:+0100                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART:19011213T211538                                                                                                                                                                                                                                                                                                                                                                                                         
RDATE;VALUE=DATE-TIME:19011213T211538                                                                                                                                                                                                                                                                                                                                                                                           
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                    
BEGIN:DAYLIGHT                                                                                                                                                                                                                                                                                                                                                                                                                  
TZNAME:CEST                                                                                                                                                                                                                                                                                                                                                                                                                     
TZOFFSETFROM:+0100                                                                                                                                                                                                                                                                                                                                                                                                              
TZOFFSETTO:+0200                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART:19810329T020000                                                                                                                                                                                                                                                                                                                                                                                                         
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3                                                                                                                                                                                                                                                                                                                                                                                          
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:DAYLIGHT                                                                                                                                                                                                                                                                                                                                                                                                                    
BEGIN:DAYLIGHT                                                                                                                                                                                                                                                                                                                                                                                                                  
TZNAME:CEST                                                                                                                                                                                                                                                                                                                                                                                                                     
TZOFFSETFROM:+0100                                                                                                                                                                                                                                                                                                                                                                                                              
TZOFFSETTO:+0200                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART:19410505T010000                                                                                                                                                                                                                                                                                                                                                                                                         
RDATE;VALUE=DATE-TIME:19410505T010000                                                                                                                                                                                                                                                                                                                                                                                           
RDATE;VALUE=DATE-TIME:19420504T010000                                                                                                                                                                                                                                                                                                                                                                                           
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:DAYLIGHT                                                                                                                                                                                                                                                                                                                                                                                                                    
BEGIN:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                  
TZNAME:CET                                                                                                                                                                                                                                                                                                                                                                                                                      
TZOFFSETFROM:+0200                                                                                                                                                                                                                                                                                                                                                                                                              
TZOFFSETTO:+0100                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART:19810927T030000                                                                                                                                                                                                                                                                                                                                                                                                         
RRULE:FREQ=YEARLY;COUNT=15;BYDAY=-1SU;BYMONTH=9                                                                                                                                                                                                                                                                                                                                                                                 
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                    
BEGIN:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                  
TZNAME:CET                                                                                                                                                                                                                                                                                                                                                                                                                      
TZOFFSETFROM:+0200                                                                                                                                                                                                                                                                                                                                                                                                              
TZOFFSETTO:+0100                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART:19961027T030000                                                                                                                                                                                                                                                                                                                                                                                                         
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10                                                                                                                                                                                                                                                                                                                                                                                         
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                    
BEGIN:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                  
TZNAME:CET                                                                                                                                                                                                                                                                                                                                                                                                                      
TZOFFSETFROM:+0200                                                                                                                                                                                                                                                                                                                                                                                                              
TZOFFSETTO:+0100                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART:19411006T020000                                                                                                                                                                                                                                                                                                                                                                                                         
RDATE;VALUE=DATE-TIME:19411006T020000                                                                                                                                                                                                                                                                                                                                                                                           
RDATE;VALUE=DATE-TIME:19421005T020000                                                                                                                                                                                                                                                                                                                                                                                           
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:STANDARD                                                                                                                                                                                                                                                                                                                                                                                                                    
X-RADICALE-NAME:Europe/Zurich                                                                                                                                                                                                                                                                                                                                                                                                   
END:VTIMEZONE                                                                                                                                                                                                                                                                                                                                                                                                                   
BEGIN:VEVENT                                                                                                                                                                                                                                                                                                                                                                                                                    
DTSTAMP:20170302T112452Z                                                                                                                                                                                                                                                                                                                                                                                                        
X-MOZ-GENERATION:1                                                                                                                                                                                                                                                                                                                                                                                                              
X-MOZ-LASTACK:20160611T194959Z                                                                                                                                                                                                                                                                                                                                                                                                  
X-RADICALE-NAME:a180a5c0-d94a-450d-b035-ffeea119e79b.ics                                                                                                                                                                                                                                                                                                                                                                        
CREATED:20170224T123957Z                                                                                                                                                                                                                                                                                                                                                                                                        
UID:a180a5c0-d94a-450d-b035-ffeea119e79b                                                                                                                                                                                                                                                                                                                                                                                        
LAST-MODIFIED:20170302T112452Z                                                                                                                                                                                                                                                                                                                                                                                                  
SUMMARY:Summary                                                                                                                                                                                                                                                                                                                                                                                                                 
STATUS:CONFIRMED                                                                                                                                                                                                                                                                                                                                                                                                                
DTSTART;TZID=Europe/Zurich:20160610T170000                                                                                                                                                                                                                                                                                                                                                                                      
DTEND;TZID=Europe/Zurich:20160610T180000                                                                                                                                                                                                                                                                                                                                                                                        
TRANSP:OPAQUE                                                                                                                                                                                                                                                                                                                                                                                                                   
BEGIN:VALARM                                                                                                                                                                                                                                                                                                                                                                                                                    
DESCRIPTION:Description                                                                                                                                                                                                                                                                                                                                                                                                         
ACTION:DISPLAY                                                                                                                                                                                                                                                                                                                                                                                                                  
TRIGGER;VALUE=DURATION:-PT10M                                                                                                                                                                                                                                                                                                                                                                                                   
X-KDE-KCALCORE-ENABLED:TRUE                                                                                                                                                                                                                                                                                                                                                                                                     
X-RADICALE-NAME:a180a5c0-d94a-450d-b035-ffeea119e79b.ics                                                                                                                                                                                                                                                                                                                                                                        
END:VALARM                                                                                                                                                                                                                                                                                                                                                                                                                      
END:VEVENT                                                                                                                                                                                                                                                                                                                                                                                                                      
END:VCALENDAR                                                                                                                                                                                                                                                                                                                                                                                                                   
"""                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                
event = icalendar.Event.from_ical(event_str) 
```

If that doesn't fail, you could search for a file that breaks with this script:

```python
import icalendar
import sys

for name in sys.argv[1:]:
    try:
        event = icalendar.Event.from_ical(open(name, 'r').read())
    except AttributeError:
        print('problem with file: {}'.format(name))
        break
```
invoke with `python filename.py path/to/vdir/*.ics`.

**Comment by in0rdr** [comment]
You are right. This script works perfectly fine, I cannot reproduce this now either..
I have to figure this out for myself. Thank you for the "trail/error" script, I'll give it a try.

I could even import the `event_str` the way you have formatted it above as .ics file without problem into khal.

But I found out, that the actual event .ics file I had on my computer was a bit larger, because there where several `VTIMEZONE` parts. See here the original file that gives you the error `'NoneType' object has no attribute 'tzinfo'` if you do a `khal import` with this file: https://pastebin.com/raw/8sDx2Uv8

Also, if you apply your test script from above on this file it will give you:
```
$ python3 testscript.py a180a5c0-d94a-450d-b035-ffeea119e79b.ics 
problem with file: a180a5c0-d94a-450d-b035-ffeea119e79b.ics
```

I do not know why there need to be the other `VTIMEZONE` parts inside this .ics file, because the actual event only needs the Europe/Zurich timezone, right?

**Comment by geier** [comment]
Thanks! I have located and fixed the issue, see https://github.com/collective/icalendar/tree/fix/timezone_count, I'll create a test and PR tomorrow, then it'll only need to be released. 

If you are comfortable with python, you can install icalendar from that branch for now.

**Comment by in0rdr** [comment]
Works perfectly with this patch.
I'm a big fan of your app, keep up the good work!

Thanks

**Comment by geier** [comment]
I'll reopen this as a reminder for me to actually fix this in icalendar.

**Comment by geier** [comment]
see https://github.com/collective/icalendar/pull/234
