### ISSUE TITLE
khal list now crashes on master

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/khal#693]
Running `khal list now` crashes no master (but not 0.9.6) (I've latest git on one machine and latest stable on the other 😉 ).

```
$ khal list now       
Traceback (most recent call last):          
  File "/usr/bin/khal", line 5, in <module> 
    main_khal()       
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__           
    return self.main(*args, **kwargs)       
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main               
    rv = self.invoke(ctx)                   
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke            
    return _process_result(sub_ctx.command.invoke(sub_ctx))                              
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke             
    return ctx.invoke(self.callback, **ctx.params)                                       
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke             
    return callback(*args, **kwargs)        
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func      
    return f(get_current_context(), *args, **kwargs)                                     
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 319, in klist                
    env={"calendars": ctx.obj['conf']['calendars']}                                      
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 224, in khal_list    
    default_timedelta_datetime=conf['default']['timedelta'],                             
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 140, in start_end_from_daterange
    default_timedelta_datetime=default_timedelta_datetime,                               
  File "/usr/lib/python3.6/site-packages/khal/parse_datetime.py", line 340, in guessrangefstr
    start, allday = guessdatetimefstr(split, locale)                                     
  File "/usr/lib/python3.6/site-packages/khal/parse_datetime.py", line 230, in guessdatetimefstr
    dtstart = fun(dtime_list, dtformat)     
  File "/usr/lib/python3.6/site-packages/khal/parse_datetime.py", line 69, in datetimefstr
    dtstart = dt.datetime.strptime(dtstring, dtformat)                                   
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime                
    tt, fraction = _strptime(data_string, format)                                        
  File "/usr/lib/python3.6/_strptime.py", line 345, in _strptime                         
    format_regex = _TimeRE_cache.compile(format)                                         
  File "/usr/lib/python3.6/_strptime.py", line 275, in compile                           
    return re_compile(self.pattern(format), IGNORECASE)                                  
  File "/usr/lib/python3.6/re.py", line 233, in compile                                  
    return _compile(pattern, flags)         
  File "/usr/lib/python3.6/re.py", line 301, in _compile                                 
    p = sre_compile.compile(pattern, flags) 
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile                         
    p = sre_parse.parse(p, flags)           
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse                             
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)                         
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub                        
    not nested and not items))              
  File "/usr/lib/python3.6/sre_parse.py", line 759, in _parse                            
    raise source.error(err.msg, len(name) + 1) from None                                 
sre_constants.error: redefinition of group name 'm' as group 7; was group 2 at position 160
```

**Comment by geier** [comment]
Are you sure this isn't a problem with your python installation? I
haven't seen dt.datetime.strptime(dtstring, dtformat) throwing that kind
of errors before.  Otherwise: if you can, please reproduce on travis.

Quoting Hugo Osvaldo Barrera (2017-07-31 16:03:55)

**Comment by geier** [comment]
@hobarrera any news on this?

**Comment by hobarrera** [comment]
This happens for `khal list now` but not `khal list`.

I can reproduce this in a virtualenv with:

```
atomicwrites==1.1.5
click==6.7
click-log==0.1.8
configobj==5.0.6
icalendar==3.11.6
khal==0.9.7.dev35+g621a9e6
python-dateutil==2.6.1
pytz==2017.2
pyxdg==0.25
six==1.10.0
tzlocal==1.4
urwid==1.3.1
```
(quick way to generate this env is `pip install git+git://github.com/pimutils/khal.git && pip install click==0.1.8`)

```
$ python --version
Python 3.6.2
```

This [somewhat ugly] tests can reproduce it (you can dump this into `cli_test.py` to run it quickly):
```python
def test_list_now(runner, tmpdir):
    runner = runner()

    xdg_config_home = tmpdir.join('.config')
    config_file = xdg_config_home.join('khal').join('config')
    config_file.write("""
        [calendars]
        [[one]]
        path = {}
        color = dark blue

        [[two]]
        path = {}
        color = dark green

        [[three]]
        path = {}

        [locale]
        longdateformat = %a %Y-%m-%d
        dateformat = %Y-%m-%d
    """.format(
            tmpdir.join('calendar'),
            tmpdir.join('calendar2'),
            tmpdir.join('calendar3'),
        ))

    result = runner.invoke(main_khal, ['list', 'now'])
    assert not result.exception
```

That's mostly based on my config file (which I now realize I never posted):
```ini
[calendars]

  [[birthdays]]
  path = ~/.local/share/contacts/cards/
  type = birthdays
  color = light magenta

  [[calendars]]
  path = ~/.local/share/calendars/*
  type = discover

[locale]
longdateformat = %a %Y-%m-%d
dateformat = %Y-%m-%d

[default]
timedelta = 8 days

[view]
agenda_event_format = "{calendar-color}{start-end-time-style} {title}{repeat-symbol}{reset}"
dynamic_days = False

# vim: ft=dosini
```

**Comment by geier** [comment]
@WhyNotHugo is this still a problem?
