### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by nolash** [pimutils/khal#699]
Khal crashes when running interactive mode virtual terminal. Works fine when run in X with eg. urxvt.

```
Traceback (most recent call last):
  File "/home/lash/data/src/virtualenv/khal/lib/python3.6/site-packages/khal/ui/__init__.py", line 1300, in start_pane
    loop.run()
  File "/home/lash/data/src/virtualenv/khal/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/lash/data/src/virtualenv/khal/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/lash/data/src/virtualenv/khal/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/lash/data/src/virtualenv/khal/lib/python3.6/site-packages/urwid/main_loop.py", line 703, in _loop
    ready, w, err = select.select(fds, [], fds, timeout)
OSError: [Errno 9] Bad file descriptor
```

Using version 0.9.6 on linux 4.11.3-1-ARCH, vdirsyncer 0.16.0

**Comment by hobarrera** [comment]
Running `ikhal` on a virtual terminal (<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>f2</kbd>) works for me. Non-ascii characters don't render properly, but that's just the font being used really. Everything else seems to work.

Any extra info you can provide? Just in case: have other curses-based apps work okay for you?

**Comment by geier** [comment]
Could you perhaps clone [urwid](https://github.com/urwid/urwid) and run the [examples](https://github.com/urwid/urwid/tree/master/examples)?

**Comment by geier** [comment]
Did you perhaps have a chance to run the urwid examples?

**Comment by nolash** [comment]
Sorry, forgot. Fails too:

```
Traceback (most recent call last):
  File "bigtext.py", line 161, in <module>
    main()
  File "bigtext.py", line 158, in main
    BigTextDisplay().main()
  File "bigtext.py", line 142, in main
    self.loop.run()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 703, in _loop
    ready, w, err = select.select(fds, [], fds, timeout)
OSError: [Errno 9] Bad file descriptor
```

**Comment by geier** [comment]
No worries and thanks for testing. Unfortunately, that result means that we probably can't too much about it in khal (and also, I really have no idea how to fix this). I would suggest opening an issue at the urwid repository.

Sorry :disappointed:

**Comment by nolash** [comment]
Done: https://github.com/urwid/urwid/issues/256

**Comment by geier** [comment]
upstream issue is closed and @nolash couldn't reproduce it any more, so this seems fixed
