### ISSUE TITLE
Edit command casues TypeError: tzinfo is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by Ian2020** [pimutils/khal#729]
This seems similar to #581, but I get it even with a search term.

I installed khal from scratch on Fedora 26, ran configure, created a new calendar as suggested during the interactive process.

Then I did:

```
khal new -a private today 12pm have lunch
khal edit lunch
```

And I see:

```
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.2', 'console_scripts', 'khal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 567, in edit
    conf=ctx.obj['conf']
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 497, in edit
    end = event.end_local.replace(tzinfo=None)
TypeError: 'tzinfo' is an invalid keyword argument for this function
```

**Comment by geier** [comment]
This probably is the same error as #581, you are running khal  0.9.2, this bug has been fixed since. Please try to upgrade and see if the bug persists.

**Comment by Ian2020** [comment]
Thanks for the quick response - sorry I should have checked my version first to see if it was latest. Looks like there's an upgrade coming in Fedora 27. I'll close for now an re-open if the problem persists once I've upgraded.

**Comment by geier** [comment]
No worries.
