### ISSUE TITLE
python errors when parse is needed

### ISSUE THREAD

**Issue by mokas01** [pimutils/khal#730]
hi i have python errors every time khal has to parse (since i installed it).i had to specify i wanted to run python 3 and pip3 as i installed it to avoid pip errors, but i need help sorting this out, i think

here is what i get when i run khal new 18: 00 Awesome Event

```
$ khal new 18: 00 Awesome Event
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/khal/cli.py", line 396, in new
    format=format,
  File "/usr/local/lib/python3.5/dist-packages/khal/controllers.py", line 339, in new_from_string
    info = utils.eventinfofstr(info, conf['locale'], adjust_reasonably=True, localize=False)
  File "/usr/local/lib/python3.5/dist-packages/khal/utils.py", line 521, in eventinfofstr
    raise ValueError('Could not parse `{}`'.format(info_string))
ValueError: Could not parse `18: 00 Awesome Event`
```

Python 3.5.3
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
on debian 9
khal (0.9.8)

Thanks in advance

**Comment by geier** [comment]
try  `khal new 18:00 Awesome Event`, no space between `:` and `00`.

**Comment by mokas01** [comment]
yes it works, sorry and thank you

**Comment by geier** [comment]
You are welcome.
