### ISSUE TITLE
error importing ccc self organised sessions

### ISSUE THREAD

**Issue by whohoho** [pimutils/khal#746]
Its the khal version from pip3 (0.9.8)

wget -O friday.ics https://events.ccc.de/congress/2017/wiki/index.php/Special:Ask/-5B-5BHas-20object-20type::Event-5D-5D-20-5B-5BHas-20event-20track::Session-5D-5D/-3FHas-20event-20title%3Dsummary/-3FHas-20start-20time%3Dstart/-3FHas-20end-20time%3Dend/-3FHas-20session-20location%3Dlocation/-3FHas-20url%3Durl/-3FHas-20description%3Ddescription/format%3Dicalendar/limit%3D2342/searchlabel%3DExport-20this-20calendar-20as-20iCal/offset%3D0

khal import -a private --batch friday

Traceback (most recent call last):
  File "/home/user/.local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/khal/cli.py", line 449, in import_ics
    env={"calendars": ctx.obj['conf']['calendars']},
  File "/home/user/.local/lib/python3.5/site-packages/khal/controllers.py", line 546, in import_ics
    vevents = utils.split_ics(ics, random_uid, conf['locale']['default_timezone'])
  File "/home/user/.local/lib/python3.5/site-packages/khal/utils.py", line 622, in split_ics
    sorted(events_grouped.items())]
  File "/home/user/.local/lib/python3.5/site-packages/khal/utils.py", line 621, in <listcomp>
    return [ics_from_list(events, tzs, random_uid) for uid, events in
  File "/home/user/.local/lib/python3.5/site-packages/khal/utils.py", line 646, in ics_from_list
    sub_event = sanitize(sub_event, default_timezone=default_timezone)
  File "/home/user/.local/lib/python3.5/site-packages/khal/khalendar/utils.py", line 188, in sanitize
    raise ValueError('Event has no start time (DTSTART).')
ValueError: Event has no start time (DTSTART).

**Comment by geier** [comment]
The .ics file is not valid, because not all VEVENTs have DTSTART properties, but this really shouldn't crash khal and it should be able to import other VEVENTs from the .ics file.

**Comment by geier** [comment]
superseeded by #963
