### ISSUE TITLE
Khal configure crashing

### ISSUE THREAD

**Issue by fnurglewitz** [pimutils/khal#753]
Hi, I've got some problems when using khal 0.9.8 (had no issues with the 0.8.4 provided by debian stretch):

When doing `khal configure` the program crashes:
```
fnurglewitz@darkstar:~$ khal -v configure
debug: khal 0.9.8
What ordering of year, month, date do you want to use?
[0] year-month-day (today: 2018-02-04)
[1] day/month/year (today: 04/02/2018)
[2] month/day/year (today: 02/04/2018)
[3] Custom
Please choose one of the above options: 1
Date format: %d/%m/%Y (today as an example: 04/02/2018)

What timeformat do you want to use?
[0] 24 hour clock (recommended)
[1] 12 hour clock
Please choose one of the above options [0]: 
Time format: %H:%M (current time as an example: 08:18)

If you use vdirsyncer to sync with CalDAV servers, we can try to load its config file and add your calendars to khal's config.
Should we try to load vdirsyncer's config? [Y/n]: Y
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/khal/cli.py", line 625, in configure
    configwizard.configwizard()
  File "/usr/local/lib/python3.5/dist-packages/khal/configwizard.py", line 206, in configwizard
    vdirs = get_vdirs_from_vdirsyncer_config()
  File "/usr/local/lib/python3.5/dist-packages/khal/configwizard.py", line 119, in get_vdirs_from_vdirsyncer_config
    from vdirsyncer.cli import config
  File "/usr/lib/python3/dist-packages/vdirsyncer/cli/__init__.py", line 41, in <module>
    @click_log.init('vdirsyncer')
AttributeError: module 'click_log' has no attribute 'init'
```

`click` version is:
```
fnurglewitz@darkstar:~$ pip3 show click
Name: click
Version: 6.6
Summary: A simple wrapper around optparse for powerful command line utilities.
Home-page: http://github.com/mitsuhiko/click
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: UNKNOWN
Location: /usr/lib/python3/dist-packages
Requires: 
```

**Comment by geier** [comment]
Thank you for reporting this. How did you install khal and what version of click_log are you using?

**Comment by fnurglewitz** [comment]
Hi, I used `pip3 install khal`

click log:
```
root@darkstar:/home/fnurglewitz# pip3 show click_log
Name: click-log
Version: 0.2.1
Summary: Logging integration for Click
Home-page: https://github.com/click-contrib/click-log
Author: Markus Unterwaditzer
Author-email: markus@unterwaditzer.net
License: MIT
Location: /usr/local/lib/python3.5/dist-packages/click_log-0.2.1-py3.5.egg
Requires: click
```

**Comment by geier** [comment]
and vdirsyncer? (I'm now also available on IRC if you want)

**Comment by fnurglewitz** [comment]
```
fnurglewitz@darkstar:~$ vdirsyncer --version
vdirsyncer, version 0.17.0a1
```

**Comment by potuz** [comment]
This is in vdirsyncer and not in khal, it happens with click_log-0.2.1 but not with 0.1.8

**Comment by potuz** [comment]
In my gentoo box vdirsyncer 0.16.0 raises this bug, but 0.16.3 does not.

**Comment by geier** [comment]
Sorry for not getting back on this any sooner. I can reproduce this with click_log-0.2.1, but current versions of click_log (0.3.2) do not have this problem. I'll therefore close this issue.
