### ISSUE TITLE
Error: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware

### ISSUE THREAD

**Issue by poddarh** [pimutils/khal#767]
This is the error I get when I try to use exchange calendars through CalDAV (DavMail). This seems to be related to the issue [mentioned here](https://github.com/dateutil/dateutil/issues/620). This seems to be a recent update to `dateutil` so I'm not sure if this is an issue that was silently ignored in the past or if this is a new issue of sorts. The following is the RRULE from my ICS file:

`RRULE:FREQ=WEEKLY;UNTIL=20180319T210000Z;INTERVAL=1;BYDAY=MO;WKST=SU`

**Comment by kaiec** [comment]
I can confirm this bug. I synchronize via vdirsyncer from Google, here is a snippet from an event:

```
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20151012T161500
DTEND;TZID=Europe/Berlin:20151012T171500
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20151130T231459Z;INTERVAL=1;BYDAY=MO
```

From reading the RFC it seems that this is perfectly correct (UNTIL has to be in UTC when DTSTART uses a time-zone) and UNTIL is actually in UTC (indicated by the Z).

**Comment by Holzhaus** [comment]
I can reproduce this problem using khal 0.9.8-3 and python-dateutil 2.7.2-1 on Arch Linux.

**Comment by lucc** [comment]
I do hit this bug **even with an event generated by kahl!**
ical file (notice the PRODID):
```icalendar
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PIMUTILS.ORG//NONSGML khal / icalendar //EN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART;VALUE=DATE-TIME:20160326T030000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART;VALUE=DATE-TIME:20161029T020000
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:foo
DTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20161108T143000
DTEND;TZID=Europe/Berlin;VALUE=DATE-TIME:20161108T193000
DTSTAMP;VALUE=DATE-TIME:20161111T173130Z
UID:XSD757X2TXZ262ELDQ4EMA1FKB8ZEZKTC917
SEQUENCE:2
RRULE:FREQ=WEEKLY;UNTIL=20170411T193000Z
LOCATION:bar
END:VEVENT
END:VCALENDAR
```
Stacktrace:
```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 303, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/backend.py", line 262, in update
    self._update_impl(vevent, href, calendar)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/backend.py", line 355, in _update_impl
    dtstartend = utils.expand(vevent, href)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/utils.py", line 89, in expand
    dtstart=dtstart
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 1664, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 1547, in _parse_rfc
    tzinfos=tzinfos)
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 1506, in _parse_rfc_rrule
    return rrule(dtstart=dtstart, cache=cache, **rrkwargs)
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 461, in __init__
    'RRULE UNTIL values must be specified in UTC when DTSTART '
ValueError: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware
warning: Skipping foobar/XSD757X2TXZ262ELDQ4EMA1FKB8ZEZKTC917.ics: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware
warning: This event will not be available in khal.
```

**Comment by geier** [comment]
Can you please tell the version of dateutil you are using?

**Comment by lucc** [comment]
khal: 0.9.8
dateutil: 2.7.2
python: 3.6.5
Arch Linux

**Comment by geier** [comment]
This is due to khal not yet supporting the latest dateutil 2.7+, have a look at this [superseeding issue](https://github.com/pimutils/khal/issues/780) for a workaround until we support the latest dateutil again.

**Comment by geier** [comment]
@ludenticus with workaround I meant installing khal via pipsi, so the old dateutil gets installed alongside.
