### ISSUE TITLE
khal crash when displayname contains an apostrophe

### ISSUE THREAD

**Issue by larsthegeek** [pimutils/khal#768]
When attempting to display a calendar with a name containing an apostrophe, for example **Dad's Calendar**, khal crashed with the following error:

`Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.8', 'console_scripts', 'khal')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/khal/cli.py", line 250, in cli
    ctx.invoke(cli.commands[command])
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/khal/cli.py", line 289, in calendar
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/usr/lib/python3/dist-packages/khal/controllers.py", line 105, in calendar
    env=env,
  File "/usr/lib/python3/dist-packages/khal/controllers.py", line 264, in khal_list
    width=width,
  File "/usr/lib/python3/dist-packages/khal/controllers.py", line 182, in get_events_between
    events = sorted(collection.get_localized(start_local, end_local))
  File "/usr/lib/python3/dist-packages/khal/khalendar/khalendar.py", line 148, in <genexpr>
    return (self._cover_event(event) for event in events)
  File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 474, in get_localized
    result = self.sql_ex(sql_s.format(self._select_calendars), stuple)
  File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 218, in sql_ex
    self.cursor.execute(statement, stuple)
sqlite3.OperationalError: near "s": syntax error
`

In this case the problem was easily solved by renaming **Dad's Calendar** to **Dads Calendar**, sans apostrophe.  However, I can't imagine having an apostrophe in a calendar name is a rare thing.

I should note khal worked properly until i ran 'vdirsyncer metasync' to pull down the color and displayname data.  I doubt it matters but I'm pulling the calendar data from FastMail.

**Comment by geier** [comment]
Thank you for reporting this, should be fixed in thew master branch now.

**Comment by d7415** [comment]
Are there any plans to fix this in a release version?
