### ISSUE TITLE
Khal crashes after selecting description of event in right panel 

### ISSUE THREAD

**Issue by ign1s-fatuus** [pimutils/khal#828]
I am having an issue viewing the details of my events in the right column where the descriptions are. Each time I select the events and go to expand them by pressing Enter khal crashes. Here are the errors produced:
`warning: unknown key or subsection "color" in section "[default]"                      
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 1300, in start_pane
    loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.7/site-packages/urwid/wimp.py", line 648, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 1106, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.7/site-packages/khal/ui/base.py", line 82, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.7/site-packages/khal/ui/widgets.py", line 308, in keypress
    key = super(NextMixin, self).keypress(size, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 925, in keypress
    self.view(self.focus_event.event)
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 640, in view
    (EventDisplay(self.pane._conf, event, collection=self.pane.collection),
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 954, in __init__
    lines.append(urwid.Text('Categories: ' + event.categories))
TypeError: can only concatenate str (not "vCategory") to str
`
I am currently syncing my calendars and todo lists from my nextcloud server via vdirsyncer. I have noticed that this only happens when I create new events with khal. I have tested this by creating and importing events from my server and have found that I can expand event data on only events originating from my server but not the other way around.

**Comment by geier** [comment]
Thank you for reporting this bug, I'll have a look.

**Comment by heiderich** [comment]
I am also experiencing this problem for some events. It seems to occur for event with a category.

**Comment by mkind** [comment]
> I am also experiencing this problem for some events. It seems to occur for event with a category.

Recently experiencing the same for events without any category.

**Comment by jolars** [comment]
I have this problem too, but only for events with categories.

**Comment by geier** [comment]
I can't reproduce this anymore on the latest master version, please re-open if this is still an issue for you.
