### ISSUE TITLE
khal crashes when importing an ICS file: TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by muelli** [pimutils/khal#838]
I've just installed khal for the first time through pip, executed khal configure and then khal import my.ics. It crashed with this stacktrace:

```
Traceback (most recent call last):
  File "/tmp/gks3/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/tmp/gks3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/gks3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/gks3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/gks3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/gks3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/gks3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/gks3/lib/python3.6/site-packages/khal/cli.py", line 454, in import_ics
    env={"calendars": ctx.obj['conf']['calendars']},
  File "/tmp/gks3/lib/python3.6/site-packages/khal/controllers.py", line 546, in import_ics
    vevents = utils.split_ics(ics, random_uid, conf['locale']['default_timezone'])
  File "/tmp/gks3/lib/python3.6/site-packages/khal/utils.py", line 612, in split_ics
    cal = icalendar.Calendar.from_ical(ics)
  File "/tmp/gks3/lib/python3.6/site-packages/icalendar/cal.py", line 369, in from_ical
    _timezone_cache[component['TZID']] = component.to_tz()
  File "/tmp/gks3/lib/python3.6/site-packages/icalendar/cal.py", line 615, in to_tz
    transitions.sort()
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by geier** [comment]
This is obviously a very shitty first contact with khal, sorry about that! ☹️ 

There either is a problem with the icalendar library or with one of your .ics files. If you could by any chance find out which .ics file is causing this and then remove non-anonymous parts, I could have a look at the problem. Without this info, it is very hard to diagnose this bug.
