### ISSUE TITLE
I broke kahl and to todoman upgrading to Ubuntu 18.04

### ISSUE THREAD

**Issue by frrobert2** [pimutils/khal#939]
I was running khal, todoman, and vdirsyncer on Ubuntu 16.04.  I upgraded to Ubuntu 18.04 and reinstalled all three programs vidirsyncer seems to be working but with both khal and todoman I get the errors listed below.

I am assuming it is not the programs themselves but they are looking for some python library  that is not in the same spot as before.  I am not a programmer so I am over my head on you to fix it.

Thanks for any advice you can provide.

ToDo Man
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (todoman 3.3.0 (/usr/lib/python3/dist-packages), Requirement.parse('todoman==3.7.0.post26+ng1e9d149'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/todo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'todoman==3.7.0.post26+ng1e9d149' distribution was not found and is required by the application
```
ikhal
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (khal 0.9.8 (/usr/lib/python3/dist-packages), Requirement.parse('khal==0.10.2.dev55+nga401ef2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/khal", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'khal==0.10.2.dev55+nga401ef2' distribution was not found and is required by the application
```

**Comment by d7415** [comment]
How did you install them?

**Comment by frrobert2** [comment]
After the upgrade I reinstalled them from the repos.

**Comment by WhyNotHugo** [comment]
There seems to be something very wrong. You're trying to run todoman 3.3.0, but it claims it's looking for todoman 3.7.0.

Maybe you installed it in two different ways? `3.3.0` was a couple of years old, so maybe you had installed via `pip install` at the time, and now you've got two installations mixed up (original `pip` one, and current `apt` one).

Can you uninstall todoman, first via you package manager, then via `pip uninstall todoman`?

If you try to run `todo`, do you get a simple `command not found`, or is there anything left over? After uninstalling both ways, what's the output of `find /usr/lib -iname "*todoman*"`? I want to make sure all copies of it are gone _before_ reinstalling it.

**Comment by frrobert2** [comment]
WhyNotHugo,
Your idea worked but I had to do it manually.  pip said there was nothing to uninstall.  I found a version of todoman and khal sitting in /usr/local/bin and libraries in /usr/local/python3.5/dist-packages I removed all those files and reinstalled  from the repo and everything works.

Thanks again

**Comment by WhyNotHugo** [comment]
It's very likely that your python version changed during the upgrade, so the libraries were in `.../python3.5`, but your current python is a newer one.

Glad it's working!
