### ISSUE TITLE
iKhal crashes with UnboundLocalError, khal version 0.10.2

### ISSUE THREAD

**Issue by tfinke** [pimutils/khal#950]
Dear Maintainers

after successful start ikhal keeps crashing with this traceback
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/khal/ui/__init__.py", line 1348, in start_pane
    loop.run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 285, in run
    self._run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 383, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 787, in run
    self._loop()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 815, in _loop
    self._entering_idle()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 776, in _entering_idle
    callback()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 571, in entering_idle
    self.draw_screen()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 585, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/wimp.py", line 637, in render
    self._update_overlay(size, focus)
  File "/usr/lib64/python3.6/site-packages/urwid/wimp.py", line 617, in _update_overlay
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1085, in render
    focus and self.focus_part == 'body')
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3.6/site-packages/khal/ui/__init__.py", line 1155, in render
    rval = super(ClassicView, self).render(size, focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 1764, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 2086, in render
    focus = focus and self.focus_position == i)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 1764, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3.6/site-packages/khal/ui/__init__.py", line 933, in render
    return super().render(a, focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 1764, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1528, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/usr/lib64/python3.6/site-packages/urwid/widget.py", line 143, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3.6/site-packages/khal/ui/__init__.py", line 284, in render
    self.body._autoextend()
  File "/usr/lib/python3.6/site-packages/khal/ui/__init__.py", line 452, in _autoextend
    pile = self._get_events(self._last_day)
  File "/usr/lib/python3.6/site-packages/khal/ui/__init__.py", line 477, in _get_events
    self.events = sorted(self._collection.get_events_on(day))
  File "/usr/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 144, in get_localized
    yield self._construct_event(*args)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 245, in _construct_event
    readonly=self._calendars[calendar]['readonly'],
  File "/usr/lib/python3.6/site-packages/khal/khalendar/event.py", line 153, in fromString
    calendar_collection = cal_from_ics(event_str)
  File "/usr/lib/python3.6/site-packages/khal/icalendar.py", line 498, in cal_from_ics
    return cal
UnboundLocalError: local variable 'cal' referenced before assignment
```

It seems the crash is caused by some entry, but I cannot figure out which one that might be.
The error disapperas sometimes after deleting of `khal.db`. 

Besides that, every variable should be properly initialized.,

Best regards

T.

**Comment by d7415** [comment]
Related: #905 (although those didn't seem to crash)

[This](https://github.com/d7415/khal/commit/040b9a5618761f72e199879ed7771ce7563498ff) might help with debugging.

**Comment by ephase** [comment]
Hi @tfinke,
Can you test it with the [master branch of Icalendar](https://github.com/collective/icalendar) and make a return. they merged a pr that avoid some 'local variable 'cal' referenced before assignment' problem.

I tested some problematic events with the same error here and all seems to work.
