### ISSUE TITLE
Deleting an event causes an error when closing ikhal (and does not delete the event)

### ISSUE THREAD

**Issue by gfarrell** [pimutils/khal#960]
I have a recurring event in my diary of which I'm trying to delete two instances. When I go to the day, press `enter` to select the event, and then `d` to delete it, the `D` flag pops up next to it to indicate it is scheduled to be deleted as per the documentation.

When I close `ikhal`, however, I get the following error, and when I reopen it, the event is still there:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/khal/ui/__init__.py", line 1348, in start_pane
    loop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 519, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 565, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/lib/python3.8/site-packages/khal/ui/base.py", line 204, in on_key_press
    self.backtrack()
  File "/usr/lib/python3.8/site-packages/khal/ui/base.py", line 189, in backtrack
    cb(data)
  File "/usr/lib/python3.8/site-packages/khal/ui/__init__.py", line 1104, in cleanup
    self.collection.update(event)
  File "/usr/lib/python3.8/site-packages/khal/khalendar/khalendar.py", line 167, in update
    assert event.etag
AssertionError
```

**Comment by ephase** [comment]
Hi @gfarrell , I think this issue is a duplicate of #793. I'm working on it.

**Comment by gfarrell** [comment]
Hi @ephase I think you're right, I'll close the issue and follow the original. Sorry for missing that!
