### ISSUE TITLE
Crash on startup: locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by frankgerhardt** [pimutils/khal#995]
```
$ python -m khal -v --version
Traceback (most recent call last):
  File "/home/siena/bin/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/siena/bin/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/siena/bin/anaconda3/lib/python3.7/site-packages/khal/__main__.py", line 22, in <module>
    from khal.cli import main_khal
  File "/home/siena/bin/anaconda3/lib/python3.7/site-packages/khal/cli.py", line 33, in <module>
    from . import __version__, controllers, khalendar
  File "/home/siena/bin/anaconda3/lib/python3.7/site-packages/khal/controllers.py", line 32, in <module>
    from khal import (__productname__, __version__, calendar_display,
  File "/home/siena/bin/anaconda3/lib/python3.7/site-packages/khal/calendar_display.py", line 31, in <module>
    setlocale(LC_ALL, '')
  File "/home/siena/bin/anaconda3/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I have no idea what locale I'm using. I never had problems with it. This happens on Debian 10 but not on Debian 9.

```
$ echo $LANG
de_DE.UTF-8

$ echo $LANGUAGE 
en_US
```

**Comment by d7415** [comment]
Try running `locale` and `locale -a`. The error implies that the locale selected isn't installed - the first command should show which locale it is trying to load (as `LC_ALL`) and the second will show which are installed.

You may need to run `sudo dpkg-reconfigure locales`.

**Comment by frankgerhardt** [comment]
Thanks. My locales were broken. I fixed it and khal works now.
