### ISSUE TITLE
Hitting new event keybinding in event search causes crash

### ISSUE THREAD

**Issue by fredthomsen** [pimutils/khal#997]
When entering search context and hitting new event a `TypeError` crashes ikhal.

version: v0.10.3.dev24+g5e5db0b.d20210103
STR:
- open ikhal
- search for anything (doesn't matter if the search gets results or not)
- hit `n`

Not sure what the behavior should be here, if it's desirable to have ikhal to enter the event creation dialog from here.

```Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/khal/ui/__init__.py", line 1348, in start_pane
    loop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.8/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.8/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.8/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.8/site-packages/khal/ui/base.py", line 114, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3.8/site-packages/khal/ui/widgets.py", line 308, in keypress
    key = super(NextMixin, self).keypress(size, key)
  File "/usr/lib/python3.8/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3.8/site-packages/khal/ui/__init__.py", line 900, in keypress
    self.new(self.focus_date, None)
  File "/usr/lib/python3.8/site-packages/khal/ui/__init__.py", line 875, in new
    start = dt.datetime.combine(date, dt.time(dt.datetime.now().hour))
TypeError: combine() argument 1 must be datetime.date, not None```

**Comment by ephase** [comment]
Hi @fredthomsen, I could reproduce the bug, found the origin and working on a solution.

**Comment by fredthomsen** [comment]
@ephase ok.  I assume this will probably apply to some other actions that can be taken from the search context as well.

**Comment by ephase** [comment]
I didn't find any other crash on search context, I submit a PR a minute ago.
